### ISSUE TITLE
Bot does not pull new posts from Subreddit RSS posts

### ISSUE THREAD

**Issue by Bewinxed** [synzen/Discord.RSS#10]
Hello, Lovely bot, working great for my RSS stream

I have tried to add a subreddit feed like so:

`https://www.reddit.com/r/dubai/.rss`

With a custom Embed and all, however, New posts do not trigger the bot

What could be the cause?

**Comment by synzen** [comment]
It might've been offline at the time of the post. If you had `sendOldMessages` set to false and restarted the bot, it won't send any messages uncaught during its downtime.

Adding something like https://www.reddit.com/new/.rss works fine for me

**Comment by l3d00m** [comment]
You should use https://www.reddit.com/r/dubai/**new**.rss, that's your problem.

**Comment by synzen** [comment]
All the reddit feeds are formatted exactly the same as far as I know, so there wouldn't be any difference in procedure between any subreddits. 

Regardless I've just tried minutes ago when a new post was submitted to /r/dubai and I saw no issues as it was posted.

**Comment by Bewinxed** [comment]
Yes i just tried it and it worked again, it's self hosted in my case so i
dunno :) thanks anyways
