### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Kadantte** [synzen/Discord.RSS#100]
Yo, First thank's for creating this lovely Bot.
How about add Set Status CMD like setusername or setavatar the CMD for Status will be something like setstatus.

https://discord.js.org/#/docs/main/master/class/ClientUser?scrollTo=setStatus

**Comment by synzen** [comment]
Just to make sure, are you aware of config `config.bot.status`? https://github.com/synzen/Discord.RSS/wiki/Configuration#bot

**Comment by Kadantte** [comment]
I know there's an option from config file but what i was thinking how about to do it with a command?

**Comment by synzen** [comment]
There you go: https://github.com/synzen/Discord.RSS/commit/614bc94e5cf373cb64d0d55a88e0f974a47b0be1

Note that it's on the dev-web branch and not on master
