### ISSUE TITLE
Where did everything go?

### ISSUE THREAD

**Issue by Bluscream** [synzen/Discord.RSS#101]
Where is the invite link of the official version to get into my server and where did the support discord go?

**Comment by synzen** [comment]
Hey there, you can always find the relevant links by googling discord.rss - it'll always be the first result

![image](https://user-images.githubusercontent.com/18688793/55520401-2c298d00-564a-11e9-8b9c-0d5007fbb963.png)

**Comment by Bluscream** [comment]
The first Result is a reddit post for me. Why not put that info in the readme?
