### ISSUE TITLE
Custom message too short

### ISSUE THREAD

**Issue by felixlinker** [synzen/Discord.RSS#106]
I just configured the bot for a server and tested it, the test results were:

```
[Title]: {title}
Schiff aus Sternenhafen gestohlen

[Description]: {description}
Das Schiff eines unabhängigen Piloten wurde aus dem Hangar eines Sternenhafens im System Vega entwendet.
Der Besitzer, ein gewisser Kommandant Bjorn Lennox, sagte Vox Galactica:
„Ich hatte mit meiner Diamondback Explorer an Bord von Fort Dixon angedockt, um einige Wartungsarbeiten durchführen zu lassen und mir nach einer langen Forschungsreise eine kleine Auszeit zu gönnen. Als ich zum Landeplatz zurückkam, musste ich feststellen, dass der Hangar leer und mein Schiff spurlos verschwund [...]

**(Truncated description for shorter rsstest)**

[Published Date]: {date}
Mon, 6 May 2019, 5:52 PM EDT
```

Unfortunately, when I use `{description}` in a custom message, the description gets truncated resulting into:

> Das Schiff eines unabhängigen Piloten wurde aus dem Hangar eines Sternenhafens im System Vega entwendet.
Der Besitzer, ein gewisser Kommandant Bjorn Lennox, sagte Vox Galactica:
„Ich hatte mit meiner Diamondback Explorer an Bord von Fort Dixon angedockt, um einige Wartungsarbeiten durchführen zu lassen und mir nach einer langen Forschungsreise eine kleine Auszeit zu gönnen. Als ich zum Landeplatz zurückkam, musste ich feststellen, dass der Hangar leer und mein Schiff spurlos verschwunden war!“
Der Sternenhafen veröffentlichte kurz daraufhin folgendes Statement von Sicherheitschefin Misaki Sanders:
„Wir wissen bisher nicht, wie es dem Dieb gelungen ist, unser Sicherheitsnetzwerk auszuhebeln, sich Zutritt zu einem angedockten und versiegelten Schiff zu verschaffen und damit anschli...

I'd like to have the option to display the full message no matter what.

**Comment by synzen** [comment]
This is possible if you enable message splitting via the command `rssplit`

**Comment by Bluscream** [comment]
Embed limits say ~1000 chars per section
