### ISSUE TITLE
~rssroles doesnt work

### ISSUE THREAD

**Issue by ScarVite** [synzen/Discord.RSS#109]

**Comment by ScarVite** [comment]
[]http://light-theme-hurts.my-ey.es/7M4Nj7m.png

**Comment by synzen** [comment]
The command is now rssmention. Please read the changelogs https://github.com/synzen/Discord.RSS/releases to stay informed of any changes when updating, and see https://github.com/synzen/Discord.RSS/wiki/Discord-Commands for a list of commands.
