### ISSUE TITLE
error when doing "npm install"

### ISSUE THREAD

**Issue by RBGaming** [synzen/Discord.RSS#11]
i got an error when doing the npm install. and it made this log file
https://www.dropbox.com/s/o9u18zzbe26tv6l/npm-debug.log?dl=0

**Comment by synzen** [comment]
Have you tried starting the bot regardless?

**Comment by RBGaming** [comment]
yep. and this happens http://imgur.com/a/abP4Y

**Comment by synzen** [comment]
Try `npm install sqlite3` and just record the logs from that particular installation attempt

**Comment by RBGaming** [comment]
it said " 'npm' is not recognized as an internal or external command, operable program or batch file."

**Comment by synzen** [comment]
You'll have look up on how to install node package manager (npm) for your OS then if for whatever train it wasn't installed when you installed Node.js. And make sure Node.js is updated which can be check with `node - v`.
