### ISSUE TITLE
Persistent Storage Docker

### ISSUE THREAD

**Issue by rob1998** [synzen/Discord.RSS#110]
Hey, probably a stupid question but I can't seem to get persistent storage working for the docker container. I would really like it, because that way I can also easily backup my settings, etc.
Any hints?

**Comment by synzen** [comment]
I don't think I understand what you mean persistent storage - can you clarify that, or what the problem is exactly? If you'd like to do something like export your settings, use the rssbackup command, and to re-import them into another container for example use the restore command
