### ISSUE TITLE
Client db connection (redis)

### ISSUE THREAD

**Issue by Dancbeunny98** [synzen/Discord.RSS#124]
![image](https://user-images.githubusercontent.com/37336183/64068213-851f4080-cc3d-11e9-8708-4ecc70c8988d.png)

**Comment by synzen** [comment]
Please clarify your issue by explaining what the problem is, and/or changing your title to something that makes more sense than "ptero dont start bot" - your screenshot shows no issues

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/64068797-f3680100-cc45-11e9-9b66-1dcbca1659aa.png)


  "database": {
    "uri": "mongodb://localhost:27017/rss",
    "redis": "redis://login:password@localhost:6379",
    "connection": {},
    "clean": true,
    "articlesExpire": 14,
    "guildBackupsExpire": 7
  },

**Comment by Feniksovich** [comment]
We installed the bot without Pterodactyl Panel, but we have Redis connection issue now. All access credentals are valid (it's checked throw phpRedisAdmin panel). The screenshot of issue above.

**Comment by synzen** [comment]
Thanks for the details. Try `redis://localhost:6379?password=<password>`

**Comment by Feniksovich** [comment]
I tried to replace <password> with password in "requirepass" password (which in redis.conf) and I still have this issue.

**Comment by synzen** [comment]
`config.database.redis` is passed directly into `redis.createClient` (see https://github.com/NodeRedis/node_redis#rediscreateclient , the `url` property) so the only reason I can only think of two reasons why it would not be working - either the credentials are wrong (if a password is indeed in redis.conf), or the URI format is wrong.

I just tried it myself with a `requirepass` in redis.conf and the above URI I mentioned worked fine. Can you paste your modified URI here, just to confirm (omitting the password)

**Comment by Dancbeunny98** [comment]
Yes. We all do so. We enter data from the created database (login and password). We enter our IP address. Enter the port. But writes that the data is not correct.

**Comment by synzen** [comment]
Put this snippet in a file
```js
const redis = require('redis')
const config = require('./config.json')
const client = redis.createClient(config.database.redis)

client.on('error', err => {
  console.log('Error', err)
})

client.on('ready', () => {
  console.log('Ready')
})

client.on('connect', () => {
  console.log('connected')
})
```

next to config.json, run it by `node file.js` and see if connects

**Comment by Feniksovich** [comment]
Hi. I created `file.js` with your code snippet and I got the following:

`root@furnex /var/www/discordrss # node file.js
Connecting to URI redis://0.0.0.0:6379?password=<PASSWORD>
connected
Error { ReplyError: ERR invalid password
    at parseError (/var/www/discordrss/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/var/www/discordrss/node_modules/redis-parser/lib/parser.js:303:14)
  command: 'AUTH',
  args:
   [ '<PASSWORD>' ],
  code: 'ERR' }
Error { ReplyError: Ready check failed: NOAUTH Authentication required.
    at parseError (/var/www/discordrss/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/var/www/discordrss/node_modules/redis-parser/lib/parser.js:303:14) command: 'INFO', code: 'NOAUTH' }`

I replaced "requirepass" password to `<PASSWORD>`.
And I used `redis://0.0.0.0:6379?password=<PASSWORD>` in config.json.

**Comment by synzen** [comment]
This, again, confirms that either the URI is written incorrectly, or the password is wrong.

Try encoding your password and using that instead (https://www.urlencoder.org/). If you have special characters in your password, then, like using any other URL, it may mess up.

**Comment by Feniksovich** [comment]
Yes indeed. Our password contained special characters and the error was fixed using encoding. Thank you very much for your answers, the issue will be closed.

Now we have another problem with the web panel, and we expect what might be the problem. If we cannot solve it, we will create a new issue.

Good Luck 🍀
