### ISSUE TITLE
Allow +rssmention to non-managers but limit to self-use

### ISSUE THREAD

**Issue by Windyo** [synzen/Discord.RSS#127]
Title.
We can't really have roles-based management in our server due to current structure and scalability.
It'd be great if users could self-sub, but only self-sub, to +rssmention

**Comment by synzen** [comment]
See https://github.com/synzen/Discord.RSS/wiki/Discord-Commands#user-commands

You may be misunderstanding how rssmention works - rssmention marks marks to be available for self-assignment by users
