### ISSUE TITLE
Heroku PORT env variable broken?

### ISSUE THREAD

**Issue by Macley-Kun** [synzen/Discord.RSS#128]
Heya S64!

Today i got an email that my D.rss bot went down.

I looked trough the logs, but noticed it suddenly doesn't want to connect with the PORT env variable?

I also noticed some things changed with the branches. So i decided to re-do my fork and test again (with dev branch).

For some reason the issue still persist.. I wanted to message you on Discord, but it seems that Discord is down atm...

Did you happen to remove the PORT env variable? Do you also experience your web-proces failing on Heroku?

Hope to hear from ya soon!

Logging:
https://pastebin.com/CTMJshxp

**Comment by Macley-Kun** [comment]
So i looked a bit deeper, and noticed some env variables have changed!
![image](https://user-images.githubusercontent.com/26381427/70380611-4b498e80-193e-11ea-87c6-921f083d4713.png)

Not sure if the PORT is still there, but that one is needed for users on Heroku...

**Comment by Macley-Kun** [comment]
After a bit more digging, I noticed the process.env.PORT
Is missing from the now default DEV branch. Perhaps that is the reason it isn’t set on the variable that check does.

**Comment by synzen** [comment]
Looks like I overlooked it - the port env variables is different on dev branch now, see https://github.com/synzen/Discord.RSS/pull/118#issuecomment-522372052

But I still forgot to account for `PORT` as you mentioned on dev branch - the latest commit https://github.com/synzen/Discord.RSS/commit/554a60519d5848ce43fcc66c488e29db98f26e53 should fix it, let me know if it works

**Comment by Macley-Kun** [comment]
So I just updated my fork. But it still gives the error sadly..

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: synzen <notifications@github.com>
Verzonden: zondag, december 8, 2019 2:35 PM
Aan: synzen/Discord.RSS
CC: Macley; Author
Onderwerp: Re: [synzen/Discord.RSS] Heroku PORT env variable broken? (#128)


Looks like I overlooked it - the port env variables is different on dev branch now, see #118 (comment)<https://github.com/synzen/Discord.RSS/pull/118#issuecomment-522372052>

But I still forgot to account for PORT as you mentioned on dev branch - the latest commit 554a605<https://github.com/synzen/Discord.RSS/commit/554a60519d5848ce43fcc66c488e29db98f26e53> should fix it, let me know if it works

**Comment by synzen** [comment]
Alright it should be fixed now as of https://github.com/synzen/Discord.RSS/commit/136aa552c680165d0e0b926f6bc122e63ee87d19

**Comment by Macley-Kun** [comment]
Ok so thanks for adding a little bit more of logging! That really helps alot where the exact problem might be!

So the PORT seems fixed! Thank you so much! I do see that i have the following error:
``Error: Missing required info for web (Client ID Exists: true, Client Secret Exists: false, Web Port Exists: true)``
so DRSS_WEB_CLIENT_SECRET isn't correct anymore?

**Comment by synzen** [comment]
no, as I mentioned before the env variables are different on dev branch since they automatically generated now, see https://github.com/synzen/Discord.RSS/pull/118#issuecomment-522372052

**Comment by Macley-Kun** [comment]
ah ok, but how does one set it trough Heroku then? Because the only way to set variables is trough the dashboard:
![image](https://user-images.githubusercontent.com/26381427/70392390-08d88e00-19e0-11ea-8a61-e2b8c7dab3c4.png)

**Comment by Macley-Kun** [comment]
Thanks dude, i needed a second to realise how it now works.
I'll make a pull to reflect these changes to the app.json.
just gotta check all the env variables :-) expect a pull request this evening! (3 hours or less)

**Comment by Macley-Kun** [comment]
nvm, it seems you've already checked that aswell! Cheers dude! Thanks for making such an awsome yet simple to manage bot!
