### ISSUE TITLE
Restore not working

### ISSUE THREAD

**Issue by rob1998** [synzen/Discord.RSS#129]
Hi, I finally had the time to setup my docker instance.
But now I want to move all my feeds with their corresponding settings from discordrss.xyz to my docker.
I backed up the config, then uploaded it in Discord and tried to use the restore command
I have tried the following commands with and without my prefix:
restore
rssrestore

First I got "No ID found", but then I discovered that my environment key was probably wrong.
This was with key "DRSS_BOT_CONTROLLER_IDS" and my user id as a string as value

Then I saw that the key should be DRSS_BOT_CONTROLLERIDS and the value should be an array containing string. But this way I don't get any result at all.

Is my latest environment key & value format correct?
And should the user id only contain numbers? for example, this is the format of my DRSS_BOT_CONTROLLERIDS key now, all digits changed to 0:
["000000000000000000"]

**Comment by synzen** [comment]
Hi, sorry for the late reply

If it says No ID Found, then you have permission to use the command, but you did not pass the server ID as an argument to the command:
![image](https://user-images.githubusercontent.com/18688793/70736990-8c93c280-1cdf-11ea-8fd0-954c39144c00.png)

**Comment by rob1998** [comment]
Thanks!
I succesfully restored it now.
