### ISSUE TITLE
Magnetic link?

### ISSUE THREAD

**Issue by f3ck4r** [synzen/Discord.RSS#130]
Why the bot not take into account the magnetic link but instead only the 'http' part of the link?

![Anotação 2019-12-10 152005](https://user-images.githubusercontent.com/26763836/70557046-d609d380-1b60-11ea-96c1-cf1796677c89.png)

**Comment by synzen** [comment]
Whether or not the text is converted into an anchor link (blue and clickable) is what Discord does - users (which includes bots) have no way to convert text to anchor links

**Comment by Bluscream** [comment]
You can make them clickable by using them in an embed

**Comment by f3ck4r** [comment]
thank you!
