### ISSUE TITLE
Editing config in Docker container

### ISSUE THREAD

**Issue by WiseMMO** [synzen/Discord.RSS#136]
Is there no way to mount a volume on host from the docker container so that I can modify the config.json easily without having to exec into the container or any other ugly looking ways?

**Comment by synzen** [comment]
You should be using the environmental variables (as specified in the steps at https://github.com/synzen/Discord.RSS/wiki/Docker) to pass in the details to config.json, but for whatever reason if you insist on directly modifying the config, you can use bind mounts (https://docs.docker.com/storage/bind-mounts/) to have the container reference the file on your host file system
