### ISSUE TITLE
Multi-paragraph blockquotes incorrectly handled.

### ISSUE THREAD

**Issue by Tantusar** [synzen/Discord.RSS#140]
If an RSS entry contains a blockquote that contains multiple paragraphs, only the first of those paragraphs is recognised as part of a quote by Discord.RSS. Multi-paragraph blockquotes must include  a `>` at the start of every paragraph (and at the start of every blank line, if any, between those paragraphs) to be correctly interpreted as one quote. Discord.RSS does not appear to be doing this.

**Comment by synzen** [comment]
If you have an example feed then I can take a closer look.

Otherwise, generally speaking, items are not added onto articles for niche cases

**Comment by Tantusar** [comment]
https://blognomic.com/feed_atom "In principio", it's a little finnicky, might need a refresh or two.

![image](https://user-images.githubusercontent.com/5593775/73702188-0aa0a280-4740-11ea-89df-7eb5d86d5b9c.png)

The last paragraph should be taken as part of the quote directly before it.

**Comment by synzen** [comment]
This is an issue related to the html-to-text package - I've submitted a PR to fix it on their repo https://github.com/werk85/node-html-to-text/pull/193 but unfortunately it looks like they don't maintain it anymore so it's unlikely to be merged.

I copied the same fix here on dev branch. If you're using the public bot though, it won't be available until the next major version release - but if you self host, the fix will be available

**Comment by KillyMXI** [comment]
@synzen Thank you for your PR. It is now merged.
