### ISSUE TITLE
[BUG] Empy Embed Message

### ISSUE THREAD

**Issue by BlackYuzia** [synzen/Discord.RSS#145]
**Describe the bug**
This is a bug with empty embed message.
If u setup color value and then remove them.
U get bug with empty embed message.

**To Reproduce**
1. Go to control panel
2. Then choose any rss and setup Embed message
![image](https://user-images.githubusercontent.com/25010528/75119889-b1b59180-568f-11ea-8103-c2476e7bf75d.png)
3. Setup color value
4. Then save.
5. Remove color value
6. wait when u get rss message.
7. get this shit:
![image](https://user-images.githubusercontent.com/25010528/75119924-fc370e00-568f-11ea-8a15-e0d7dca4a1b4.png)

**Expected behavior**

**Screenshots**

**Branch (please specify one):**
master

**Additional context**
I can't fully remove color option of embed message.
So ... **I can't fully remove embed message?**

**Comment by synzen** [comment]
Thanks for the report. I saw that you were referring to the public bot - I've fixed the issue on there now.

For the record, you can edit or remove embeds through Discord commands
