### ISSUE TITLE
[Feature request] Add the ability for self-subscriptions without roles.

### ISSUE THREAD

**Issue by Soitora** [synzen/Discord.RSS#146]
**Is your feature request related to a problem? Please describe.**
Currently my problem is related to me haveing a feed of over 30 unique articles per week that rotates on a quarterly basis. One article has maybe 5 users at most that is subscribed, combined with the amount of unique articles and the rotation, having roles is inefficient and bulky. In my case 

I've experienced that user subscriptions are much smoother and don't have to deal with the inefficiencies of having roles (as long as the subscriptions per article is kept relatively low).

The actual problem is that users can only manually subscribe themselves to pre-setup roles, and not as individual user mentions. This is possible for the admin via the backup file or the WebUI, but it's not feasable having the admin having to add/remove users from their specified article requested.

**Describe the solution you'd like**
Right now I'd just like for the user to have the ability to subscribe themselves to articles. Basically right now I just add a filter to them that includes the article title, which in turn mentions them when an article matching the criteria is found.

**Additional context**
This would help running Discord.RSS more headless. Less work for the admins as well. Of course there's the issue of 10-100s+ users per article. This is only feasable with low-subscription articles. Maybe limit user mentions on an article to 10?

**Comment by synzen** [comment]
Thanks for the suggestion, it's definitely something I want to look into. I'll see if I can get this in before v6. If not, then it'll definitely be in v6.1

**Comment by synzen** [comment]
Good news - this has now been implemented in v6. The option to allow users to directly add themselves must be enabled in `options` first, then users will be able to add themselves within the `sub` command menu.

**Comment by Soitora** [comment]
Awesome, thanks!
