### ISSUE TITLE
[Feature Request] Share Custom Embed and Text Templates Between Feeds

### ISSUE THREAD

**Issue by BlackYuzia** [synzen/Discord.RSS#148]
**Is your feature request related to a problem? Please describe.**
This is feature for add us (users) backup created message embed settings (like: color, message, author, timestamp etc)

And then, if we need it. use this backup for other feeds.

**Describe the solution you'd like**
Can't do it clearly... but if simple: 
**add function to save backup**. 
**add function to load backup**.

**Additional context**
I want this feature (maybe others too) because I have some feeds what have the same embed and text message.
So I need copy the same template again and again in all my not different (my eng best) feeds.

**Comment by synzen** [comment]
Hi, you can use the `rssclone` command (or `clone` command on dev branch) to copy settings from one feed to one or more other feeds
