### ISSUE TITLE
Unable to start dev docker image

### ISSUE THREAD

**Issue by grainz** [synzen/Discord.RSS#149]
**Describe the bug**
This outputs to the log when starting the container:
`(node:17) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'warn' of undefined
    at Client.login (/app/src/structs/Client.js:66:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**To Reproduce**
Create a fresh docker container with synzen/discord.rss:dev

**Branch (please specify one):**
dev

**Comment by synzen** [comment]
Thanks for the report, https://github.com/synzen/Discord.RSS/commit/3306b25c1ea0801db5b9d597b16b11990cd538b0 should fix this TypeError
