### ISSUE TITLE
server.js line18 error on launch

### ISSUE THREAD

**Issue by nEo-1664** [synzen/Discord.RSS#15]
Using a Ubuntu16.04 server install, followed the wiki, and had a few errors with sqlite3, but got past those, but now getting this error on launch. GCC and G++ are installed, and npm install ran OK under sudo. 

Any thoughts?

server.js:18
    let c = 0
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by synzen** [comment]
Is your node.js version at least v6?

**Comment by nEo-1664** [comment]
Had to run the following in order to get nodejs >=6.

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by synzen** [comment]
Yeah, that's as indicated on the installation instructions for installing it via a package manager on Debian/Ubuntu https://nodejs.org/en/download/package-manager/. After updating, it should run without that error
