### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by misszeestar** [synzen/Discord.RSS#155]
**Describe the bug**
502 Bad Gateway on the website. Therefore, no feeds are working.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Branch (please specify one):**
master, dev, or public bot

**Additional context**

**Comment by synzen** [comment]
The public site https://discordrss.xyz will be disabled until the next major version release, v6, for performance reasons. It has just been has been updated to reflect this. Be assured that the site is only there as a convenience, and has no impact on your publicly hosted feeds.

Apologies for any inconvenience.
