### ISSUE TITLE
Setgame command and prefix bug

### ISSUE THREAD

**Issue by StrangeRanger** [synzen/Discord.RSS#156]
**Describe the bug**
When using the command `setgame`, instead of only recognizing the command with the given/current prefix, it will set a game with any prefix. Say my prefix is `~`, but I use `_`, it will still set the game.

**To Reproduce**
1. Use `setgame` with a prefix that is not the default/currently set prefix.

**Expected behavior**
It not to set a game, unless the currently set prefix is used.

**Screenshots**
<img width="894" alt="Screen Shot 2020-03-25 at 8 59 53 PM" src="https://user-images.githubusercontent.com/30395560/77608869-9e3e5600-6edb-11ea-8013-9f2a31892d2e.png">

**Branch (please specify one):**
master

**Comment by synzen** [comment]
Thanks for the report, 5.0.6 fixes this now (https://github.com/synzen/Discord.RSS/commit/7b0b4e6a2504fcb8d7eb4c018d81fec330d89eb0)
