### ISSUE TITLE
Bot doesn't respond to any commands

### ISSUE THREAD

**Issue by jondycz** [synzen/Discord.RSS#162]
Using commands from your documentation, bot is online, never responded. Using the publicly hosted instance.

**Comment by TheLovinator1** [comment]
The prefix has been changed. The prefix is now rss instead of ~. So "rss.help" instead of "~rsshelp"

From [Discord](https://discordapp.com/channels/268797598926766090/282014867420872704/713461941246361662):

> - The prefix has been changed to rss.. For example, the correct syntax is rss.command1 now instead of ~command1 with the previous prefix.
> - All commands that started with rss, such as rssadd, has the rss removed. So ~rssadd is now rss.add (with the new prefix), ~rssmove is now rss.move, etc.
> - The command rssmessage has been renamed to text (so rss.text)
> - The command subme has been renamed to sub (so rss.sub)
> - The command unsubme has been renamed to unsub (so rss.unsub)

**Comment by jondycz** [comment]
I tried all the prefixes. ~ - ! . 

When I sent the messages, it was 12:59, the bot responded at 7:10PM that's 6 hours later. So I don't think prefix was the issue. Anyway, seems to work now. If such downtimes occur often, I might have to find an alternative.

**Comment by synzen** [comment]
Please do not open issues regarding the public bot in the Github repos. There is a Discord server dedicated to support specific to the public hosting of the bot. In the future, please follow the [contributing guidelines](https://github.com/synzen/Discord.RSS/blob/dev/CONTRIBUTING.md):

![image](https://user-images.githubusercontent.com/18688793/82932253-2251a000-9f56-11ea-91cb-0ea66c0eb5bc.png)

>**The issue tracker is only for technical support, bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord](https://discord.gg/pudv7Rx) server instead of opening an issue.**
