### ISSUE TITLE
Command that lists all the feeds ONLY in the current channel

### ISSUE THREAD

**Issue by StrangeRanger** [synzen/Discord.RSS#163]
**Is your feature request related to a problem? Please describe.**
If I want to list all of the feeds in a guild, I can obviously use `rss.list`. But if I just want to list all the feeds in a current channel, there is no way of doing that.

**Describe the solution you'd like**
It'd be really helpful and nice to have a command or a flag added to the `rss.list` command such as `rss.list local` that would list all of the feeds only in the current channel.

**Comment by synzen** [comment]
Thanks for the suggestion. Something like it has now been implemented (https://github.com/synzen/Discord.RSS/commit/995bdb83a61140a8d03c100af10eb3880633e0b8). Add a channel mention as an argument to `list`, and it will only show the feeds within the mentioned channel. Once it's merged into master and released, I'll close this.

**Comment by synzen** [comment]
Published in [6.1.0](https://github.com/synzen/Discord.RSS/releases/tag/6.1.0)
