### ISSUE TITLE
Bring back the ability to select a range of feeds using `x-y` on commands such as `rss.clone`

### ISSUE THREAD

**Issue by StrangeRanger** [synzen/Discord.RSS#166]
**Is your feature request related to a problem? Please describe.**
In the previous major version (v5.x.x), when cloning or performing an action that allowed you to select many feeds, you were able to use `x-y,z,a`, but now it's only possible `x,y,z,a`. This makes it really annoying when I want to, say, clone certain text/embedded properties from feed 1 to feeds 2-80.  

**Describe the solution you'd like**
Please bring back to the ability to select a  range of feeds using `x-y` when performing actions that allow the user to pick multiple feeds, instead of only being able to individual reference/choose a feed using `x,y,z,a`.

**Comment by synzen** [comment]
Thanks for the suggestion. I intended to reimplement this but it had slipped my mind. I'll try to get it in the next patch.

**Comment by synzen** [comment]
This is now available in v6.3.9
