### ISSUE TITLE
What permissions does the bot need?

### ISSUE THREAD

**Issue by ArtOfCode-** [synzen/Discord.RSS#167]
I've set up a self-hosted instance, but I can't add feeds. Each time I use `rss.add`, there's an error in the terminal:

```
[2020-06-07 15:45:35.692 +0000] INFO : [0] Used add
    message: "rss.add https://writing.codidact.com/categories/2/feed.rss https://meta.codidact.com/categories/10/feed.rss https://meta.codidact.com/categories/21/feed.rss https://meta.codidact.com/categories/3/feed.rss https://outdoors.codidact.com/categories/6/feed.rss https://localhost:3000/categories/12/feed.rss https://photography.codidact.com/categories/14/feed.rss https://scientific-speculation.codidact.com/categories/16/feed.rss https://cooking.codidact.com/categories/18/feed.rss https://electrical.codidact.com/categories/27/feed.rss"
    guild: "634104110131445811, Codidact"
    channel: "707191199571640402, meta-posts"
    user: "355501251947134996, ArtOfCode"
[2020-06-07 15:45:35.792 +0000] WARN  (DiscordAPIError): [0] Message listener (50013 permission error)
    DiscordAPIError: Missing Permissions
        at RequestHandler.execute (/var/apps/discordrss/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Same thing happens if I only use one feed link.

What permissions does the bot need? I've given it everything that seems relevant, but perhaps I'm missing something:

 * Manage Channels (?)
 * Change Nickname
 * Manage Webhooks
 * View Channels
 * all Text permissions except Mention Everyone

**Comment by Bluscream** [comment]
why would it need to change its own nickname?

**Comment by synzen** [comment]
All it needs is `Read Messages` and `Send Messages` for the add command. If it can't respond to you with that error, then it doesn't have send messages permission in the channel you're using it in

**Comment by ArtOfCode-** [comment]
> it doesn't have send messages permission in the channel you're using it in

As always... simplest solution is easiest solution... I was trying to use it in a read-only channel without realising. Cheers!
