### ISSUE TITLE
A command that checks if a given feed has already been added to the server

### ISSUE THREAD

**Issue by StrangeRanger** [synzen/Discord.RSS#168]
**Is your feature request related to a problem? Please describe.**
I find myself running into the trouble, especially when it comes to Reddit feeds, remembering whether or not I've already added a certain feed to the current server. There is no QUICK and EASY of finding this out, other than manually looking through the feeds using `rss.list`.

**Describe the solution you'd like**
Add a command that you can use in any channel, that can check if a given feed has already been added to the server/list. Something similar to this: `rss.check [feed url]`

**Comment by synzen** [comment]
Thanks for the suggestion. I'll look into adding the ability to query (search for) feeds via `rss.list` arguments.

**Comment by synzen** [comment]
v6.4 now has this implemented.
