### ISSUE TITLE
Created Filter, now filter screen is blank

### ISSUE THREAD

**Issue by Dschogo** [synzen/Discord.RSS#169]
**Describe the bug**
Added a filter. After that the screen got blank (the backgroundcolor of discord / this site).
The rest of the control panel works fine. (using the official site: https://discordrss.xyz/)
Tried to: reload page, delete cookies, use another browser

**To Reproduce**
1. Create filter and press "add"

**Expected behavior**
The normal page and nothing blank

**Screenshots**
![image](https://user-images.githubusercontent.com/36862419/84591081-d8b0f280-ae3b-11ea-853a-e2e082e39cfa.png)

I think the html is not delivered correctly: (container for the elements is empty):
![image](https://user-images.githubusercontent.com/36862419/84591186-b075c380-ae3c-11ea-95ce-38f98543c36a.png)

**Branch (please specify one):**
dunno, think the master

**Comment by synzen** [comment]
Thanks for the report, it's now been fixed. For future reference, please direct anything related to the web at https://github.com/synzen/Discord.RSS-Web - this repository is only for the bot
