### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by freakyy85** [synzen/Discord.RSS#17]
Hi!

I don't know how I can run the bot, and how I do install dependencies. Is there any quick howto on how to get the bot up and running? :)

Thanks! :)

**Comment by synzen** [comment]
Uh what... It says right there on the main page readme for steps on how to set it up on your own click the link to the wiki.

**Comment by freakyy85** [comment]
oh sorry I didn't see that. Thank you. Though I'm having a problem with npm install now:

make: Leaving directory '/home/uwe/Discord.RSS/node_modules/node-opus/build'

> sodium@2.0.1 install /home/uwe/Discord.RSS/node_modules/sodium
> node install.js --install

echo Build node-sodium module
Build node-sodium module
node-gyp rebuild
make[1]: Entering directory '/home/uwe/Discord.RSS/node_modules/sodium/build'
  CXX(target) Release/obj.target/sodium/src/crypto_aead.o
  CXX(target) Release/obj.target/sodium/src/crypto_sign.o
  CXX(target) Release/obj.target/sodium/src/crypto_sign_ed25519.o
  CXX(target) Release/obj.target/sodium/src/crypto_box.o
  CXX(target) Release/obj.target/sodium/src/crypto_box_curve25519xsalsa20poly1305.o
  CXX(target) Release/obj.target/sodium/src/sodium_runtime.o
  CXX(target) Release/obj.target/sodium/src/crypto_auth.o
  CXX(target) Release/obj.target/sodium/src/crypto_auth_algos.o
  CXX(target) Release/obj.target/sodium/src/crypto_core.o
  CXX(target) Release/obj.target/sodium/src/crypto_scalarmult_curve25519.o
  CXX(target) Release/obj.target/sodium/src/crypto_scalarmult.o
  CXX(target) Release/obj.target/sodium/src/crypto_secretbox_xsalsa20poly1305.o
  CXX(target) Release/obj.target/sodium/src/crypto_secretbox.o
  CXX(target) Release/obj.target/sodium/src/sodium.o
  CXX(target) Release/obj.target/sodium/src/crypto_stream.o
  CXX(target) Release/obj.target/sodium/src/crypto_streams.o
  CXX(target) Release/obj.target/sodium/src/helpers.o
  CXX(target) Release/obj.target/sodium/src/randombytes.o
  CXX(target) Release/obj.target/sodium/src/crypto_pwhash.o
  CXX(target) Release/obj.target/sodium/src/crypto_hash.o
  CXX(target) Release/obj.target/sodium/src/crypto_hash_sha256.o
  CXX(target) Release/obj.target/sodium/src/crypto_hash_sha512.o
  CXX(target) Release/obj.target/sodium/src/crypto_shorthash.o
  CXX(target) Release/obj.target/sodium/src/crypto_shorthash_siphash24.o
  CXX(target) Release/obj.target/sodium/src/crypto_generichash.o
  CXX(target) Release/obj.target/sodium/src/crypto_generichash_blake2b.o
  CXX(target) Release/obj.target/sodium/src/crypto_onetimeauth.o
  CXX(target) Release/obj.target/sodium/src/crypto_onetimeauth_poly1305.o
  SOLINK_MODULE(target) Release/obj.target/sodium.node
  COPY Release/sodium.node
make[1]: Leaving directory '/home/uwe/Discord.RSS/node_modules/sodium/build'
npm ERR! Linux 4.4.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package erlpack@0.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer discord.js@11.1.0 wants erlpack@hammerandchisel/erlpack

npm ERR! Please include the following file with any support request:
npm ERR!     /home/uwe/Discord.RSS/npm-debug.log

Can you help me?

**Comment by synzen** [comment]
As part of step#1, and indicated by your logs,

> npm ERR! node v4.8.3
> npm ERR! npm v2.15.11

please make sure you have a non-outdated version of node.js installed. One of the two version as shown on the main page: https://nodejs.org/en/

**Comment by freakyy85** [comment]
Thank you very much it worked now! :)
