### ISSUE TITLE
Cloudflare - 1020, Access Denied (Custom Firewall Rules)

### ISSUE THREAD

**Issue by NathanielRMoss** [synzen/Discord.RSS#171]
**Describe the bug**
Feed used to work a few days ago. Rss.refresh gives this error. Wanted to document it as I couldnt find a google result for it. 

**To Reproduce**
On my discord server, using rss.refresh results in this error:
The following feed(s) failed to refresh:
https://www.apkmirror.com/apk/niantic-inc/pokemon-go/feed/
Reason: Cloudflare - 1020, Access Denied (Custom Firewall Rules)
 

**Expected behavior**
The feed to be added.

**Screenshots**

**Branch (please specify one):**
 public bot

**Additional context**
Also all apkmirror links are now "blocked" on my discord.

**Comment by Bluscream** [comment]
What do you mean by links are blocked?

**Comment by NathanielRMoss** [comment]
Getting this same error.

**Comment by synzen** [comment]
Thanks for the report. Unfortunately, the bot cannot bypass Cloudflare protections - see https://github.com/synzen/Discord.RSS-Clone/issues/9 for more details.

Cloudflare can be activated/deactivated at its own or at the website's discretion at any time, which will block bots from accessing the site.

**Comment by Bluscream** [comment]
Would projects like https://github.com/Anorov/cloudflare-scrape not work for the bot?

**Comment by synzen** [comment]
The two you mentioned are for python, and the third one is deprecated (as it says on the `README` in huge letters). I have not found any open-source working and up-to-date solution for this in JS - but if you do find one, you can definitely let me know.
