### ISSUE TITLE
Typo on documentation

### ISSUE THREAD

**Issue by MicaelJarniac** [synzen/Discord.RSS#174]
**Describe the bug**
Typo in the documentation.

**To Reproduce**
1. Go to https://docs.discordrss.xyz/configuration/discord-commands#guild-manager-commands
1. Scroll down to `list`
1. See typo in Arguments (`[<channel mentiion>] [query]`)

**Expected behavior**
`[<channel mention>] [query]`

**Screenshots**
![Typo](https://i.imgur.com/HMRXfxN.png)

**Branch (please specify one):**
I have no idea where the docs are stored.

**Comment by synzen** [comment]
Thanks, fixed.
