### ISSUE TITLE
Bot is not accepting private messages

### ISSUE THREAD

**Issue by jannyba** [synzen/Discord.RSS#177]
hi

I can talk to bot on public servers in a channel, but why is he not recognizing commands send by private message?
thanks

**Comment by synzen** [comment]
Hi, 

It does not respond to DMs because commands are not meant to be used in DMs, only servers where feeds are added.

**Comment by jannyba** [comment]
so the public will see the commands? hmm ok... I will rather disable commands and use web gui

**Comment by synzen** [comment]
The public only sees what you allow them to see - using commands with a bot is no different than chatting with a person. You may adjust Discord permissions to only let people see what you want them to see.
