### ISSUE TITLE
Docker step by step installation guide

### ISSUE THREAD

**Issue by jannyba** [synzen/Discord.RSS#178]
Hi
please add docker steb by step guide, for example I have these hints and question:
- looks like I need git clone RSSClone repository and only then run docker-compose command? how the update works then? I need update docker or the clonned files?
- list of the required packages at start of the guide (docker, docker-compose)
- where exactly is the file to set env variables? in the clonned repository folder or somewhere inside the docker folder?
- env file with all values will be great, the same way as we have bot and web example configs

thanks

**Comment by synzen** [comment]
Hi,

If you use Docker, you're expected to already understand the fundamentals of Docker. If you don't yet have a fundamental understanding of Docker, I suggest you go through https://docs.docker.com/get-started/ and optionally https://docs.docker.com/compose/ for Docker Compose.

To more directly answer your questions:

1. You need to recreate your container based on either the new image when it is published, or files when they're updated. This is only for file changes: https://stackoverflow.com/questions/41322541/rebuild-docker-container-on-file-changes
2. docker-compose is an alternative to `docker`. See https://docs.docker.com/compose/ for a better understanding of what docker-compose is.
3. Docker does not inherently use an env file that is injected into your container - you would have to use a custom solution if you want to go that route. Alternatively, you can set environment variables through the `--env` or `e` CLI argument for `docker` - see https://docs.docker.com/engine/reference/commandline/run/ for more information. If you choose to use docker-compose, the necessary env variables are already written in for you in `docker-compose.yml` - you can add more to your liking.
