### ISSUE TITLE
limit discord rss bot access to selected users

### ISSUE THREAD

**Issue by jannyba** [synzen/Discord.RSS#179]
Hi

I'm providing discord rss bot to a channels, problem is there are moderators who are not quite knowledge about commands, computing etc so I don't like that they can access www site and have access to RSS feeds, can I limit ability to access control panel only to selected users? by user ID for example..

thank you!

**Comment by synzen** [comment]
For web related questions, please direct them to https://github.com/synzen/Discord.RSS-Web/issues. 

To answer your question, unfortunately no. Everyone who has Manage Channels permission has an equal level of access to bot commands and the control panel. To do more than that would require a custom permissions system dictating who among those people has more power.
