### ISSUE TITLE
Date and time instead of the timestamp in log file

### ISSUE THREAD

**Issue by jannyba** [synzen/Discord.RSS#180]
Hi

if possible please print date and time instead of timestamp in the log files, as that is not helping when checking log files and looking for an issue, thanks!

![image](https://user-images.githubusercontent.com/56595831/90419244-98c5f000-e0b6-11ea-86e9-08a6348a0a26.png)

**Comment by synzen** [comment]
Hi, the log file is meant to be parsed by something like https://github.com/pinojs/pino-pretty where you can control how you parsed the time. If you prefer human-readable dates, I suggest you disable `config.log.destination` and instead pipe `stdout` into your own log file.
