### ISSUE TITLE
Discord.RSS does not cleanup itself when gracefully exiting

### ISSUE THREAD

**Issue by Ultima1252** [synzen/Discord.RSS#181]
**Describe the bug**
When the program's process.exit() event is called Discord.RSS does not clean up after itself and will leave leftover processes running. See comments in #26 for more details.

**To Reproduce**
1. Send SIGTERM to the main process (kill -SIGTERM $pid)

This will cause it to close and leave child processes running.

**Expected behavior**
All child processes also closing.

**Additional context**
The issue stated above provides details on how this can be fixed. Systemd systems or running in dockers may not show the same behavior because these systems may forcefully close the process tree. Init does not do this as it is the program's responsibility and not the init systems job.

I believe this can be fixed by adding a signal handler on exit that runs the [client.destroy()](https://discord.js.org/?source=post_page---------------------------#/docs/main/stable/class/Client?scrollTo=destroy) method. I also suggest cleaning up database connections and any other file descriptors open with write access.

**Comment by synzen** [comment]
Thanks for the report. This is definitely something that needs to be addressed. I'll try to get it in the next patch release

**Comment by synzen** [comment]
Release 6.5.37 should have this fixed now. Thanks for the detailed report.
