### ISSUE TITLE
Bot crashes when over 25 feeds

### ISSUE THREAD

**Issue by NateChambers** [synzen/Discord.RSS#2]
Maybe needs a multipage menu for bots that allow over 25 feeds? Like "rsslist 1" "rsslist 2" etc.

Or maybe I am doing something wrong?

Error:

Fatal Error for Commands Module! Stopping bot: printing error:

RangeError: RichEmbeds may not exceed 25 fields.

File:
node_modules/discord,js/src/structures/RichEmbed.js

Triggered By File:
commands/rsslist.js on line 31

**Comment by synzen** [comment]
Just added printing for lists greater than 10 feeds - it'll send multiple messages. A temporary fix until discord.js fixes their reaction events - then this will be replaced by pagination control via emojis.
