### ISSUE TITLE
Crashing and or bot disconnecting

### ISSUE THREAD

**Issue by givemhell** [synzen/Discord.RSS#20]
the bot will randomly disconnect and will not reconnect with the CMD window open

and sometimes the CMD window  it will just randomly disappear as if it was closed

i cant even find a crash log file, only logFeedErrs & logLinkErrs

**Comment by synzen** [comment]
The program can't close the window, that's up to you and the operating system - so something is up with your system that's causing windows to randomly close

However what you can do is use a process manager, as outlined in the wiki, and check the console output generated from the process manager in the file that it creates.

**Comment by givemhell** [comment]
its been running for a full 24 hours now with no problems, i didn't make any changes either

not sure what was causing it to close the cmd window

still waiting to see if the bot goes offline again
