### ISSUE TITLE
Bot not online 

### ISSUE THREAD

**Issue by GeorgeWL** [synzen/Discord.RSS#21]
Hello,  I'm using the version hosted by you and it has been offline for the last few days now. 

If this was intentional please let me know and I'll start the version on this git in a microserver for just me.

**Comment by synzen** [comment]
Please reserve github issues to issues about the repo/code rather than about downtime concerning the publicly hosted bot.

But in any case, hosting one yourself is always preferable over using the public one given the increased flexibility, and decreases load on the public verison.
