### ISSUE TITLE
Error is Run bot

### ISSUE THREAD

**Issue by fanatikvoice** [synzen/Discord.RSS#24]
Hi, i not running bot. Error -> https://pp.userapi.com/c836637/v836637497/67b2a/j01QRU4grbY.jpg

**Comment by TheLovinator1** [comment]
From first step: "IMPORTANT: Make sure the version installed is not an outdated one. Do NOT neglect this step."

You are running a old version. Try with a newer version. 🍮

**Comment by fanatikvoice** [comment]
How do update a via terminal? I cant install from archive from official website

**Comment by synzen** [comment]
Please follow the instructions provided by Node: https://nodejs.org/en/download/

If you're using a package manager, the instructions are linked at the bottom.
