### ISSUE TITLE
Add FreeBSD install guide and init script to wiki

### ISSUE THREAD

**Issue by Ultima1252** [synzen/Discord.RSS#26]
Install npm:
`pkg install npm`

Create discord-rss user:
`adduser`
```
Username: discord-rss
Full name:
Uid (Leave empty for default):
Login group [discord-rss]:
Login group is discord-rss. Invite discord-rss into other groups? []:
Login class [default]: daemon
Shell (sh csh tcsh nologin) [sh]: nologin
Home directory [/home/discord-rss]:
Home directory permissions (Leave empty for default):
Use password-based authentication? [yes]: no
Lock out the account after creation? [no]:
```

Switch to user discord-rss and set HOME:
`su -m discord-rss -c sh`
`HOME=/home/discord-rss`

Clone Discord.RSS:
`cd`
`git clone https://github.com/synzen/Discord.RSS.git`

Install node modules:
`cd Discord.RSS`
`npm install`

Edit config.json and anything else needed.

Once satisfied with config, exit shell session and create an rc script this this contents
`exit`
`vi /usr/local/etc/rc.d/discord-rss`
```
#! /bin/sh
#
# $FreeBSD$
#

# PROVIDE: discord_rss
# REQUIRE: DAEMON
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable discord_rss:
#
#discord_rss_enable="YES"

. /etc/rc.subr

name="discord_rss"
rcvar="discord_rss_enable"

: ${discord_rss_enable:="NO"}
: ${discord_rss_directory:="/home/discord-rss/Discord.RSS"}

user="discord-rss"
group="discord-rss"

pidfile="/var/run/discord-rss/discord-rss.pid"
command="/usr/sbin/daemon"
command_args="-rSP $pidfile -p $pidfile.child -u $user /usr/local/bin/node ${discord_rss_directory}/server.js"
discord_rss_chdir="$discord_rss_directory"
start_precmd="discord_rss_precmd"

load_rc_config $name

discord_rss_precmd()
{
        if [ ! -d "${pidfile%/?*}" ]; then
                install -d -o "$user" -g "$group" "${pidfile%/?*}"
        fi
}

run_rc_command "$1"
```
Add discord_rss_enable="YES" to /etc/rc.conf to start Discord.RSS on reboot:
`sysrc discord_rss_enable="YES"`

And finally, start Discord.RSS
`service discord-rss start`

Stdout and stderr will be redirected to syslog (/var/log/messages). If this is not desired, removing the -S options from command_args and adding -o /path/to/log should work but have not tested.

Enjoy! =]

**Comment by synzen** [comment]
Nice, I added a link to this at the beginning of https://github.com/synzen/Discord.RSS/wiki/Starting-the-Bot before step 1. Thanks for the effort!

**Comment by xylust** [comment]
After following the instructions I am faced with:

```
$ service discord-rss start
discord-rss does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
```

Did I do something wrong?

**Comment by Ultima1252** [comment]
Is it executable? ls -l /usr/local/etc/rc.d

**Comment by xylust** [comment]
It was not. Changing it to be executable produces:

`-r-xr-xr-x  1 root  wheel   831 Feb 24 00:47 discord-rss`

```
$ service discord-rss start
eval: cannot open /var/run/discord-rss/discord-rss.pid: Permission denied
Starting discord_rss.
limits: setrlimit datasize: Operation not permitted
/usr/local/etc/rc.d/discord-rss: WARNING: failed to start discord_rss
```

**Comment by Ultima1252** [comment]
You are probably starting it as the discord-rss user. Starting and stopping services requires root. You can check with the whoami command.

**Comment by Ultima1252** [comment]
I also just realized that building the sqlite3 module for npm requires python to be installed. You may encounter this error when running npm install in the Discord.RSS directory.

**Comment by xylust** [comment]
It was not working for the root user either, I must've messed something up. I re-did a new instance following the steps (only modifying `#! /bin/sh` to `#!/bin/sh` but I doubt this made any difference) which lead to success.

I now have the bot up and running. Thanks for the help @Ultima1252 !

**Comment by Ultima1252** [comment]
np, glad you got it working. =]

**Comment by xylust** [comment]
Just FYI I did not install python. Also I was about to suggest adding git as a dependency but I see you're ahead of me :)

**Comment by Ultima1252** [comment]
@xylust I would but one problem is that sudo doesn't come installed on FreeBSD by default so it wouldn't work for everyone. Instead, I added the Legends at the top to clarity what user is running the command. Do you think this is clear enough?

**Comment by xylust** [comment]
@Ultima1252 Does it not? I am using `freebsd-11-1-release-amd64` and I did not require to install sudo, I suppose not all versions include it, then?

Correct me if I am wrong but if I remember right when I first connected to my freshly installed FreeBSD my prefix was `$` (which would imply discord user in your case) and it only turned to `#` when I did `sudo -s` although this was just my experience, I have never used FreeBSD before so I am completely naive

**Comment by Ultima1252** [comment]
In [most] Unix and Unix-like shells, the default standard is for '#' stands for root and '$' for user. The su command is how to switch users and being a member of the wheel group will allow you to switch to the root user. Sudo is only available if you install the third party packages using the package manager pkg[1]. If you are using a cloud provider like amazon aws, they may come with preinstalled packages but a default, without third party package install of FreeBSD will not include sudo.

I have a feeling python was also preinstalled which is why you didn't have issues with that sqlite3 module throwing an error during npm install.

[1] https://unix.stackexchange.com/questions/116470/whats-the-sudo-equivalent-for-freebsd

**Comment by constrict** [comment]
Had some issues when upgrading to v6. See updated run script to clean child processes.

```
#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: discord_rss
# REQUIRE: DAEMON
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable discord_rss:
#
#discord_rss_enable="YES"

. /etc/rc.subr

name="discord_rss"
rcvar="discord_rss_enable"

: ${discord_rss_enable:="NO"}
: ${discord_rss_directory:="/home/discord-rss/Discord.RSS"}

user="discord-rss"
group="discord-rss"

pidfile="/var/run/discord-rss/discord-rss.pid"

command="/usr/sbin/daemon"
command_args="-rSP $pidfile -p $pidfile.child -u $user /usr/local/bin/node ${discord_rss_directory}/bot.js"
discord_rss_chdir="$discord_rss_directory"

start_precmd="discord_rss_precmd"
stop_precmd="discord_rss_stop_precmd"
stop_postcmd="discord_rss_stop_postcmd"

load_rc_config $name

discord_rss_precmd()
{
        if [ ! -d "${pidfile%/?*}" ]; then
                install -d -o "$user" -g "$group" "${pidfile%/?*}"
        fi
}

discord_rss_stop_precmd()
{
        if [ -r ${pidfile} ]; then
                pid=`cat ${pidfile} 2>/dev/null`
        fi
}

discord_rss_stop_postcmd()
{
        _DRSS_CHILDREN=$(pgrep -g ${pid})
        echo "Cleaning up leftover child processes."
        kill -9 ${_DRSS_CHILDREN}
        wait_for_pids ${_DRSS_CHILDREN}
}

run_rc_command "$1"
```

**Comment by Ultima1252** [comment]
Hey constrict,

> `kill -9 ${_DRSS_CHILDREN}`

Are you sure that killing the child processes ungracefully is necessary? I haven't kept up with the codebase so I'm not sure what needs to be cleaned up, but I would use -9 with caution. Depending on what your killing it could have harmful effects.

**Comment by lazeraman** [comment]
Yes, the shards get orphaned and don't rebind when the the app is restarted.

**Comment by constrict** [comment]
Yes, the shards get orphaned and don't rebind when the the app is restarted.

If there is a better way, I do not know it. \_('-')_/

**Comment by Ultima1252** [comment]
Hello @constrict,

Dug into the code figured out why they are not being cleaned up and I have a rough idea of how to add this functionality.

The problem is that the program, as far as I can tell, does not handle the [exit event](https://nodejs.org/api/process.html#process_event_exit) at all. When the bot receives a SIGTERM, before the program exits, it should run some code to clean itself up. This is a signal to the process telling it to gracefully shutdown. When this is received you need to run the [client.destroy()](https://discord.js.org/?source=post_page---------------------------#/docs/main/stable/class/Client?scrollTo=destroy) method which I believe should clean up all the shards.

If you would like, I could probably create a pull req for this, but it will take a while as I do not have a testing env setup for this. If you need any help feel free to reach out.

**Comment by constrict** [comment]
@Ultima1252 That would be helpful since I don't know where to include the client.destroy()

**Comment by Ultima1252** [comment]
I created a ticket for this so the devs can take a look. I mistakingly thought you were a dev on the project. Hopefully, this gets fixed so runaway processes stop invading userland! XD

**Comment by constrict** [comment]
I no longer have these any issues with orphaned process. Thanks!
