### ISSUE TITLE
What is the correct Redirect URI to pass to Discord's configs

### ISSUE THREAD

**Issue by vpontin** [synzen/Discord.RSS#29]
Noob here, just wanting to host the bot in my spare raspberry pi 3, everything is fine execpt i can't invite my bot due to MISSING RETURN URI, but in Setup section of the wiki nothing is said about this.

What is the correct URI to pass, given i dont have any webserver installed on my pi?

**Comment by synzen** [comment]
There is no redirect URI. If you followed the instructions *exactly*, there should be no issues.

**Comment by vpontin** [comment]
Well, perharps i messed up checking "Require OAuth2 Code grant" on bot settings of discord.
But just for information, what is the required permissions i need to check on the [add link generator](https://discordapi.com/permissions.html) for the bot join correctly?

**Comment by synzen** [comment]
You can give it whatever permission you want/all of them if you want - it's your hosted bot on your own server

**Comment by vpontin** [comment]
I mean, i only need to give the bot read/write messages? Idk if the bot does other moderation functions on background.
Anyway, the issue is fixed, i was able to make the bot join the server, just need to know why it wont boot via pm2 (let's leave this for another issue).
