### ISSUE TITLE
Discord Bot Token Reset Due to Potential Abuse

### ISSUE THREAD

**Issue by MooreDrums** [synzen/Discord.RSS#30]
I've received the below message twice in the past hour. I'm unsure what to check.

"It appears your bot has connected to Discord more than 1000 times within a short time period. Since this kind of behavior is usually a result of a bug we have gone ahead and reset your bot's token."

I've already reset the token, but this happened again. I've tried googling, but didn't find much information on it.

**Comment by synzen** [comment]
That is on Discord's side, assuming you are not doing anything out of the ordinary. There's nothing you can do (I had the same issues when I first started developing), but it should eventually stop.
