### ISSUE TITLE
Bot doesn't appear online when starting via pm2

### ISSUE THREAD

**Issue by vpontin** [synzen/Discord.RSS#31]
Well, starting the bot using `pm2 start path/to/Discord.RSS/server.js` shows the bot to be running and fine, but it wont became online in my server. Strangely, starting via `node /path/to/Discord.RSS/server.js` make the bot appear online and fine, but i cant do any command (using default ~ prefix).

And in pm2 the logs only say: `0|Discord. | (node:32571) ExperimentalWarning: The http2 module is an experimental API.`

Can you help me? I'm hosting on a rPi 3

**Comment by synzen** [comment]
PM2 has issues on some environments that I can't explain - I've had this issue on multiple environments. If that is the case, then you can try another module such as [forever](https://www.npmjs.com/package/forever). Make sure, as described on the wiki, you `cd` into the directory first to start the process.

**Comment by vpontin** [comment]
i think its related to what directory the terminal is cd'ed: i tried once to run the bot using `nodejs path/to/server.js` and i got several errors. But cd'ing first and running `nodejs server.js` make the bot run fine.
Now i'm running the bot at startup using rc.local and calling nodejs directly (and redirecting the bot output to a log file).

**Comment by synzen** [comment]
Yes, that is why you need to change the active directory to the one with server.js first. Node uses all the files relative to where the active directory you are in when you start server.js. Glad you got it working.

**Comment by Hostile** [comment]
it works for me node server.js

but even when cd to dir and pm2 start server.js its not going online

strange

**Comment by synzen** [comment]
Yes, that would be related to what I was describing the second comment here.
