### ISSUE TITLE
Titles in embeds stopped being clickable

### ISSUE THREAD

**Issue by vSh1ny** [synzen/Discord.RSS#37]
Just as the title says, I can no longer click on the title in the embed to open the link. Using Discord.RSS v. 2.1.0.
Example embed json:
```json
...
"random_name": {
      "title": "Unread Content",
      "link": "<rss_url>",
      "channel": "<channel_id>",
      "message": "{empty}",
      "embedMessage": {
        "enabled": 1,
        "properties": {
          "url": "{link}",
          "color": 0,
          "authorTitle": "{title}",
          "authorAvatarURL": "<image_url>",
          "thumbnailURL": "{image1}",
          "message": "{description}",
          "footerText": "Example.com | {date}"
        }
      }
    }
...
```
It worked before, but the title stopped being clickable around 3 weeks ago.

**Comment by synzen** [comment]
There was some confusion with the embed URLs in an older commit and it probably went way back to the last commit on master branch. Try replacing the files `./rss/translator/embed.js` and `./commands/rssembed.js` with the ones in dev branch. Then reset it and add the proper fields and it should work.

**Comment by vSh1ny** [comment]
Thank you! I think changing `authorTitle` to `title` property is what fixed that for me.
