### ISSUE TITLE
RSS subscription limit

### ISSUE THREAD

**Issue by Z-Doctor** [synzen/Discord.RSS#39]
This is more of a personal problem, but I would like to be able to subscribe to more than 5 feeds. Perhaps add an option to override the limit.

**Comment by DrakeTDL** [comment]
are you self-hosting it? if so, you can change the limit in the config or you can support synzen on Patreon  to raise the limit

**Comment by synzen** [comment]
^ what Drake said. Please read through the [configuration part of the wiki](https://github.com/synzen/Discord.RSS/wiki/Configuration). You can change the feed limit there.

**Comment by Z-Doctor** [comment]
Ok, I wanted an easy way to do it :P I'll read <3
