### ISSUE TITLE
Instructions to use systemd

### ISSUE THREAD

**Issue by Danpiel** [synzen/Discord.RSS#4]
Hello, I've made instructions to use systemd unit for managing Discord RSS, it will work as eny other system service with logging to systemd

Since I can't directly make a pull request to wiki, providing wiki repo with changes https://github.com/Danpiel/Discord.RSS.Wiki for manual merging.

Thanks for awesome work.

**Comment by synzen** [comment]
Added it in, thanks for the contribution!
