### ISSUE TITLE
how to install on rasberry serveur Debian ?

### ISSUE THREAD

**Issue by gamersalpha** [synzen/Discord.RSS#40]
Hello there, 

i need exatly this, to push some news on my discord channel, can u explain me how to install it on my serveur web please

**Comment by synzen** [comment]
Instructions are already provided on on the wiki which is linked on the main page README.md.

https://github.com/synzen/Discord.RSS/wiki/Starting-the-Bot

**Comment by gamersalpha** [comment]
i see, but i don"t understand nothing :/

**Comment by gamersalpha** [comment]
need help please

**Comment by synzen** [comment]
![token image](https://user-images.githubusercontent.com/18688793/36118476-2c8a7e84-100b-11e8-8c8c-e3a94124fe90.png)

Make sure you let sqlite3 finish installing with `npm install` or `npm install sqlite3`. ***Do not interrupt the process when it's not done.*** This may take a long time for some environments. You may [switch to mysql](https://github.com/synzen/Discord.RSS/wiki/Configuration#database-selection) if you don't want to use sqlite.

**Comment by gamersalpha** [comment]
sory but node is really i big mysteri for me :  


what that's means please : 


`
stagiaire@ubuntu:/var/www/html/discord_rss_bot/Discord.RSS$ sudo npm install

> sqlite3@3.1.13 install /var/www/html/discord_rss_bot/Discord.RSS/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/var/www/html/discord_rss_bot/Discord.RSS/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN discord.js@11.3.0 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of libsodium-wrappers@^0.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.

`

**Comment by synzen** [comment]
You can ignore those warnings.

**Comment by gamersalpha** [comment]
Hello so my serveur is starting : 

1> i can't se my bt in my discord channel, i can't understand how to invite him please ?

> Click "Generate OAuth2 URL" on the same page where you got your token, check the Bot scope and check whatever permissions you want it to have to generate the invite link, and invite the bot to your server.

i click on "Generate OAuth2 URL" but i have no link on it ?

![image](https://user-images.githubusercontent.com/32466950/36267003-2f2712be-1273-11e8-83f3-d7a3ce653b4f.png)

2> what config file i need to modifie to have my rss show in discors, i think need 2 informations : 
https://github.com/synzen/Discord.RSS/wiki/Custom-Message
1 - The name of discord channel to show the rss
2 - where i put a link of the rss who the bot will found ?

thanks

**Comment by gamersalpha** [comment]
ok now i sucess have my bot in discord

now i just need to understand how to add rss field in config files (what config files) and have information in my discord

**Comment by gamersalpha** [comment]
Hello so now my bot is in my discord : 
![image](https://user-images.githubusercontent.com/32466950/36268112-fa0ccbb6-1275-11e8-803b-9b305b6ab6c2.png)

but i can make it talk

missing some thinks in my config files  : 

`{
  "logging": {
    "logDates": true,
    "discordChannelLog": "",
    "showLinkErrs": true,
    "showUnfiltered": true
  },
  "botSettings": {
    "token": "dqsddsqdqsdqsdqsdqsdsqdsqdsqdsqdsqdsqdqsdsqdsqdsqdsqdsqdq",
    "enableCommands": true,
    "prefix": "~",
    "defaultGame": "",
    "controllerIds": [],
    "menuColor": 7833753,
    "deleteMenus": false
  },
  "feedManagement": {
    "sqlType": "sqlite3",
    "databaseName": "rss",
    "enableBackups": true,
    "enableRestores": false,
    "cleanDatabase": false,
    "maxEntryAge": 14
  },
  "feedSettings": {
    "refreshTimeMinutes": 15,
    "checkTitles": false,
    "timezone": "Europe/Paris",
    "timeFormat": "ddd, D MMMM YYYY, h:mm A z",
    "dateFallback": false,
    "timeFallback": false,
    "maxFeeds": 5,
    "failLimit": 0,
    "notifyFail": true,
    "sendOldMessages": false,
    "defaultMaxAge": 1,
    "cycleMaxAge": 1,
    "defaultMessage": ":newspaper:  |  **{title}**\n\n{link}\n\n{subscriptions}",
    "showRegexErrs": true,
    "imagePreviews": true,
    "imageLinksExistence": true,
    "checkDates": true
  },
  "advanced": {
    "shards": 1,
    "batchSize": 300,
    "restrictCookies": false,
    "restrictWebhooks": false,
    "processorMethod": "single",
    "minifyJSON": false
  },


"sources": {
    "name": "Github YouPHPTube - commits",
    "link": "https://github.com/DanielnetoDotCom/YouPHPTube/commits/master.atom",
    "channel": "github-youphptube",
    "message": "New commit :"
}

}


and if i try to talk to the bot, i  have no response : 

![image](https://user-images.githubusercontent.com/32466950/36268199-39a057c0-1276-11e8-9f00-414aaed15a7d.png)

what do u think please ?`

**Comment by gamersalpha** [comment]
ok so now missing, one information

how add rss on the bot and make the bot talk in the channel :/

**Comment by TheLovinator1** [comment]
"botSettings": {
    "prefix": "~",
  },

You have to type "~rsshelp"

**Comment by synzen** [comment]
Don't bother with creating JSON files... use the discord commands ~rssadd
