### ISSUE TITLE
Issue with images. Space reserved, though no picture

### ISSUE THREAD

**Issue by hAirypAulsAck** [synzen/Discord.RSS#42]
having an issue with images not loading. believe it's a bug/issue with compatibility (on their part). For the latter, feed validation passed, but with reccomendations. Regardless, the images show up in other feed aggregators and I've checked the options, everything seems to be enabled. oddly, the reserved space seems to be there, as if it knew the size of the picture, just not load. Refer to examples for this

Source:
https://forum.warthunder.com/index.php?/forum/26-project-news-read-only.xml

Examples:
https://i.imgur.com/DwthIjq.png
https://i.imgur.com/czx5Ajw.png

**Comment by synzen** [comment]
That embed (box) is unrelated to the bot - copy and paste the link yourself and you'll probably see the same thing happen to your message because Discord automatically generates it based on page metadata.

**Comment by hAirypAulsAck** [comment]
I got you, think it has something to do with them embedding the images inside the RSS description tag rather than having it within the proper image tag

```
<image>
  <url>https://www.w3schools.com/images/logo.gif</url>
  <title>W3Schools.com</title>
  <link>https://www.w3schools.com</link>
</image>
```

Like I mentioned, other RSS services/programs I used seemed to be able to spot the embedded image; is this outside limitations of the bot or rather something that just needed to be implemented. If the latter, would this be something to look into implementing?

**Comment by synzen** [comment]
As I have just said, this is unrelated to the bot. Discord automatically generates the embed based on the link's metadata. Copy the link yourself and paste it in Discord and you will see that Discord automatically creates it, *not the bot*. All it did is post a link.

![image](https://user-images.githubusercontent.com/18688793/37207973-8605d664-236d-11e8-947f-26218163b5fb.png)

**Discord reads the metadata off the link to generate the embed** - in this case, the metadata from that link is

![image](https://user-images.githubusercontent.com/18688793/37208051-e4bebae0-236d-11e8-9dfb-2185cbeb7643.png)

You can blame the website owners for generating such metadata that Discord then reads to automatically put under any messages that has that link. To provide more examples of what I mean by an automatically generated embed that Discord creates:

![image](https://user-images.githubusercontent.com/18688793/37208128-33170da0-236e-11e8-9c79-e6d8b48bf532.png)

**Comment by hAirypAulsAck** [comment]
Okay I misunderstood, this clarified it for me: 

> Copy the link yourself and paste it in Discord and you will see that Discord automatically creates it, not the bot. 

Yeah I figured it was because they didn't put the image in rss standards, I will message them eventually, thanks
