### ISSUE TITLE
Support for Heroku

### ISSUE THREAD

**Issue by Macley-Kun** [synzen/Discord.RSS#43]
Status: on hold

In the near future, when the transition from SQLite/MySQL to mongodb is fully working on stable. These docs can be used to host your selfhosted Discord.RSS. The solution provided is also known as a PaaS solution.

Todo:
x Test selfmade instruction.
x  Improve steps so everything can be done trough the git bash/heroku cli.
- Discuss placement of Procfile. Include in project or rather download?
x Issue?: not sure if a web worker is created even if procfile is used at first launch. If so, maybe look if project uses a port to contact the outside world. If using a different project's file. The web worker will work withoud dying in 90seconds.

Provided files can be used if you can't wait for it. But only ping Macley#9105 if you get any troubles.
Procfile you need to instert before ever pushing to heroku: https://mega.nz/#!XY43yT6T!8oyAxGGnv7NZ25IgmNYxrPe4kBdNFk_m4DJTfPv8I6U

**Comment by Macley-Kun** [comment]
[Instruction.v1.txt](https://github.com/synzen/Discord.RSS/files/1823022/Instruction.v1.txt)
Tried instruction, found some silly mistakes like mention to the user to copy their files to the heroku folder.
Web worker can't be used. Instead using worker. Made a extra command so users default start the worker. They don't have to worry to stop the bot. They can just keep updating and the app restarts itself.

@synzen could you do a review on this? Sorry if you don't like the format :P

**Comment by synzen** [comment]
Just tried it and it's working remarkably well. Though it might be prudent to mention that the procfile must be included in directory in the instructions

**Comment by Macley-Kun** [comment]
You sure you used the v1 file?
2. Add the all the files (Expect the .git folder) and the procfile into the folder were gonna use to push the files to Heroku. 

Says that indeed procfile needs to be added :-)

**Comment by synzen** [comment]
Ah right my mistake, yeah there it is

**Comment by synzen** [comment]
Insert into git itself?

**Comment by Macley-Kun** [comment]
Inside your git project. The discord.rss project i mean.

So users don't have to download that file seperately

**Comment by synzen** [comment]
ah have it part of the repo. yeah sure. dm me the final version of the procfile and it'll be in the next commit

**Comment by Macley-Kun** [comment]
Closing issue (after docs are up) solution:

The final tested instruction:
[Instruction Heroku Final.txt](https://github.com/synzen/Discord.RSS/files/1826486/Instruction.Heroku.Final.txt)

The final tested procfile (soon in your local Discord.RSS folder!)
https://cdn.discordapp.com/attachments/315488301886865408/425364645273010177/Procfile

**Comment by Macley-Kun** [comment]
Closed
Solved: #45 
Soon will be updated for Dev docs!
