### ISSUE TITLE
How to host Discord.RSS in Heroku!

### ISSUE THREAD

**Issue by Macley-Kun** [synzen/Discord.RSS#45]
*Read the instruction first in it's whole before continuing.*
## Pre-requirements
```
1. [Git](https://www.atlassian.com/git/tutorials/install-git).
2. [Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli).
3. A [Heroku](https://www.heroku.com/) account.
4. A working Discord.RSS project in a separate folder.
```

### Instruction

1. Make a new folder, this will be the folder where all the data will be pushed to your Heroku app.

2. Copy all the files from the working Discord.RSS project into this folder. Make sure that **you don't copy the hidden .git folder!**

3. Use git bash inside this folder. (right-click, and choose git bash here).

4. Type the following commands:
```
git init
heroku create discordrssapp
heroku addons:create mongolab:sandbox
heroku config:get MONGODB_URI
```
Change discordrssapp to a name that you like, no capital letters.

5. Copy the whole line from `mongodb`. Replace the in the config.json at the URI part the `"mongodb://localhost/rss",` with the copied MONGODB_URI. The line should look like this:
`    "uri": "mongodb://heroku_12345678:random_password@ds029017.mLab.com:29017/heroku_12345678",`
save the file and continue in git bash.

6. Type the following commands:
```
git add .
git commit -am "make it better"
git push heroku master
heroku ps:scale worker=1
heroku ps:scale web=0
```

##### Updating
You can replace the files in the folder we use for Heroku with the updated files.
To push the changes you can do the following commands:
```
git add .
git commit -am "make it better"
git push heroku master
```
Keep in mind that you don't replace the config.json!

##### Troubleshooting
- Make sure after installation of the Heroku CLI, that you type in `Heroku login` and fill in the credentials of your Heroku account.
- Check if the config.json is correct. An incorrect value/outdated file could cause problems.
- If you still stuck, check if your project runs locally correct. *replace the mongodb uri with the default one!*
- If all the above are correct, and it's not the project itself, only then you mention me: `Macley#9105`.

**Comment by Macley-Kun** [comment]
@synzen 👍

**Comment by codeinteger6** [comment]
@Macley-Kun this guide should be updated for the current version of the bot with the web UI.

**Comment by Macley-Kun** [comment]
Ah your right! Will do :-)

**Comment by Macley-Kun** [comment]
# How to deploy to Heroku the *new* way!
## Pre-requirements
1. A [Heroku](https://www.heroku.com/) account.
2. Have all the credentials you need ready!

## Instruction
1. Go to [the repo](https://github.com/synzen/Discord.RSS) and use the purple looking button to deploy directly to Heroku!
2. Fill in all the details, if you want to host the web dashboard, make sure to also do the following:
* DRSS_WEB_CLIENT_ID
* Get the CLIENT_ID by going [here](https://discordapp.com/developers/applications/). It should look like: `343394333935336303`.
* RSS_WEB_CLIENT_SECRET
* On the same page, copy the client secret.
* DRSS_WEB_ENABLED
* Set this to `true`. To enable the web part.
* DRSS_WEB_REDIRECT_URI
* Given the name you want to give to your app, make sure to replace APPNAME with yours! `https://APPNAME.herokuapp.com/authorize`. If you decide to use a domain, change the APPNAME.herokuapp.com to your domain name.
*Given my appname: `d-discordrss`. With my domain: drss.meetdelta.com. I configured it as followed:
![Example redirect uri's](https://imgur.com/HZ3Z31f.png)
* Do note that i added way to many, if you get into any problem, suggest to use both appname and domain name, in both http and https format.
3. Now hit deploy and go to Resources. Turn off Worker and turn on Web. If you now click on Open app, you should see your own dashboard!
4. Now, to keep Discord.rss up, it's recomanded to use [uptimerobot](https://uptimerobot.com/). It's easy to use and even mails you when your bot goes down! When this happens just give it a few moments or reboot it by turning the switch off and on again!
5. Given that you deployed with the button, you can choose to fork the repo, and to connect from Heroku to your app.
![How to connect Github fork to Heroku app](https://cdn-media-1.freecodecamp.org/images/ylaZsAuah1udMDvouTIQLmzLDKJX9FrC23yB)
6. Now, make sure to keep your fork up to date, you can use [this project](https://github.com/chaNcharge/ForkUpdater) to do this automatically for you! You can set these env variables in the settings tab your Heroku app. You can add the script to the root of your forked repo. The changes should emmediatly trigger a push and build to your app.
7. When that's set, go into your Heroku app to overview, and add the `Heroku Scheduler`. Configure it with the following: `bash ./update.sh` you can set the time to whatever you want.

That's it, not only haven't you installed any software, but your app will auto-update with the new dashboard working natively with Heroku!

**Comment by Macley-Kun** [comment]
Did this in a rush tho, as i'm doing quite alot at the same time :P i hope it's clear enough for everyone to follow. Let me know if it has any mistakes/improvements!

**Comment by codeinteger6** [comment]
I suggest the original post be edited instead of a new comment.

**Comment by Macley-Kun** [comment]
Well technically that old pose is so old, we didn't even had env variables or a deploy button.
The old one would be deleted, but still holds value if people don't wanna use the deploy button or with github integration.

If you want me to edit it, im gonna replace it (delete the old one).

**Comment by codeinteger6** [comment]
They can follow [this one](https://github.com/synzen/Discord.RSS/issues/95#issue-421919295) if they don't want to deploy manually. I can rename the one I wrote to a manual deploy guide, as the title `How to host without credit card` is no longer valid as Heroku recently changed their dyno hours to take down Discord bots as well when the free 550 hours are up. So if they want to try out the bot and they're not ready to verify their account, they can follow the manual deploy guide, and if they want to go with it then they can verify their card later.

**Comment by Macley-Kun** [comment]
Done!

**Comment by MicaelJarniac** [comment]
> Go to [the repo](https://github.com/synzen/Discord.RSS) and use the purple looking button to deploy directly to Heroku!
@Macley-Kun

The URL in "the repo" links to https://github.com/synzen/Discord.RSS, but I believe that the user-deployable one, with the "purple looking button" and all, is at https://github.com/synzen/Discord.RSS-Clone.

**Comment by Macley-Kun** [comment]
Ah it seems that the repository went totally different
If @synzen is ok with it, we could change the hard coded value in the button to:
`[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy)`
Souce https://devcenter.heroku.com/articles/heroku-button
Could anyone test if the above works for **everyone**?

**Comment by MicaelJarniac** [comment]
I tried it (the "manual" way, inspected element and replaced the reference to https://heroku.com/deploy) and it worked for me.

**Comment by Macley-Kun** [comment]
No need to go complicated lol
Just change the url in the adres bar or readme

Mvgr

Wesley de Vree
________________________________
Van: Micael Jarniac <notifications@github.com>
Verzonden: Friday, July 24, 2020 5:41:39 PM
Aan: synzen/Discord.RSS <Discord.RSS@noreply.github.com>
CC: Macley <wesley.de.vree@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [synzen/Discord.RSS] How to host Discord.RSS in Heroku! (#45)


I tried it (the "manual" way, inspected element and replaced the reference to https://heroku.com/deploy) and it worked for me.

**Comment by mdbennett** [comment]
I keep getting the error "Web process failed to bind to $PORT within 60 seconds of launch)" when trying to deploy on Heroku. I've been reading up online and it seems like server.js needs to be set up to be listening to a port but I can't quite figure out how to do that

**Comment by Macleykun** [comment]
Note that this repo is not meant to be ran but this one does
https://github.com/synzen/MonitoRSS-Clone
suggest everyone with questions about heroku to ask there.
Afaik, ya ran the web dyno and given you use the dashboard (make sure ya are using this) then I’m nit sure where the problem lies.
If ya do not wish to use the dashboard, use the worker dyno instead. Monitorrss is responsible for hooking in the var
