### ISSUE TITLE
Subreddit link

### ISSUE THREAD

**Issue by neveSZ** [synzen/Discord.RSS#46]
Hello everyone

How do I get the source link from a post in subreddit (not the post link)?

Like: https://www.origin.com/nld/en-us/store/free-games/on-the-house/
instead of: https://www.reddit.com/r/GameDeals/comments/8bcamt/origin_medal_of_honor_pacific_assault_0free/

RSS link: https://www.reddit.com/r/GameDeals/hot/.rss

Thanks,
Neves

**Comment by Macley-Kun** [comment]
You tried messing with `~rssmessage` ?

That's the only thing you can do with the bot, to change the ouput of the messages.

**Comment by neveSZ** [comment]
Yes, my problem is not with formatting, but with placeholders, the placeholder {link} returns me the link from the post in reddit, but I would like the link from the source(like Steam, Gog,HumbleBundle). The information I am seeking is not shown in any placeholder.

**Comment by Macley-Kun** [comment]
If the rss feeds doesn't have this. Then you have to request this at the site owner. The D.RSS bot sadly can't help you out on this on.

**Comment by neveSZ** [comment]
But if I access the page through the browser I can see the link inside the content tag along with many other information. Is there any way to get this link?

**Comment by Macley-Kun** [comment]
Then put the content tag in the ~rssmessage

it should then post the whole part of the content tag. Dus posting the link?

**Comment by neveSZ** [comment]
That's exactly what I need, thanks for the support and the wonderful bot. <3

**Comment by synzen** [comment]
Should work now

**Comment by neveSZ** [comment]
Everything working now, thanks again :D
