### ISSUE TITLE
Cannot make bot start using systemd

### ISSUE THREAD

**Issue by vpontin** [synzen/Discord.RSS#50]
Hi!
I'm trying to switch my instance's start method from rc.local to systemd. I used a variation of the script from the wiki, but the bot is looping on this error.

[Both files on the gist](https://gist.github.com/vpontin/60606e53174b9e0c4807d0416b8aaa7e).

What can i do to make it run?

Thanks in advance!

**Comment by Macley-Kun** [comment]
I actully would suggest you trying pm2. It’s easier to setup + can do the same things like systemd.

Met vriendelijke groet,

**Comment by vpontin** [comment]
I use systemd because i want to centralize my autostart stuff (i already have a couple of bots + gitbucket starting via this method)
And to add to issue, the only changes i made for this transition was switching a `-` to a underscore in the bot folder name (reflected on systemd .service file) and rename the bot on discord applications dashboard. Can one of these alterations causing this crash?

**Comment by Macley-Kun** [comment]
I think you mistyped something in your systemd file. Two paths that should be the same are different! It's actually the change you did with -. I'm sadly not able to get on pc for a couple of days. Double check your paths in systemd you'll see it quick ;)

Verstuurd vanaf mijn iPad

**Comment by vpontin** [comment]
Oh i think i found the problem: i just changed the name of `discord-rss` folder, not the parent `.discord_bots`.

Thanks a lot to help me figure out the error!
