### ISSUE TITLE
Start error after upgrading node to 10.x

### ISSUE THREAD

**Issue by vpontin** [synzen/Discord.RSS#51]
I ran with this error after trying to start the bot after updating my node to 10.x (Raspbian):
https://gist.github.com/vpontin/eb6fd1137c76a53e3bd9980b9555f8e1

Tried to npm rebuild on discord.rss folder but the compilation always end in error. https://gist.github.com/vpontin/03461aa0f684d9fa7b1edd59fa0ac364

I suspect this is something related to sqlite, but i dont know how to fix that.

**Comment by vpontin** [comment]
not worked for me.

**Comment by synzen** [comment]
As vpontin said, it's related to Node 10, not the bot. For an easy solution just downgrade Node to <10 or switch to MySQL if you can't get it working with 10

**Comment by vpontin** [comment]
Thanks @synzen , i'm afraid i need to follow the original thread because my pi is almost full and i cannot install heavy apps anymore (but i have mongodb 3.0.14 running already)

**Comment by vpontin** [comment]
https://github.com/kriasoft/node-sqlite/issues/58#issuecomment-389092643 was closed with new package. What are the directions now? Should i update the instance? Wait to @synzen update? Can i remove the file generated by `npm shrinkwrap` @shikhir-arora said to run?

**Comment by synzen** [comment]
Closing this after marking v3.0.0, dropping support for SQL and moving over to MongoDB/databaseless.
