### ISSUE TITLE
{description} includes a photo url - any way to remove it?

### ISSUE THREAD

**Issue by mastermood** [synzen/Discord.RSS#56]
![image](https://user-images.githubusercontent.com/9539678/41198155-c9fe7ada-6c40-11e8-936d-60f44b754213.png)

![image](https://user-images.githubusercontent.com/9539678/41198231-851bbbb0-6c42-11e8-8edc-61b35a7c80bd.png)

See above. I used {description} for this from https://boards.4chan.org/biz/index.rss using an ~rssembed and so I get the description but {description} also posts a photo url in the first part of its message. Any way to get rid of it/filter it?

**Comment by synzen** [comment]
Yes, ~rssoptions -> 3 (Image Links Existence for placeholders)
