### ISSUE TITLE
Disconnects intermittently - here's the log

### ISSUE THREAD

**Issue by mastermood** [synzen/Discord.RSS#57]
Jun 11 01:04:08 moodserver discord-rss[13210]:         _sender: [Object],
Jun 11 01:04:08 moodserver discord-rss[13210]:         _socket: [Object],
Jun 11 01:04:08 moodserver discord-rss[13210]:         _error: null,
Jun 11 01:04:08 moodserver discord-rss[13210]:         url: 'wss://gateway.discord.gg/?v=6&encoding=json',
Jun 11 01:04:08 moodserver discord-rss[13210]:         _req: null },
Jun 11 01:04:08 moodserver discord-rss[13210]:      type: 'error',
Jun 11 01:04:08 moodserver discord-rss[13210]:      message: 'read ECONNRESET',
Jun 11 01:04:08 moodserver discord-rss[13210]:      error: { Error: read ECONNRESET
Jun 11 01:04:08 moodserver discord-rss[13210]:     at _errnoException (util.js:992:11)
Jun 11 01:04:08 moodserver discord-rss[13210]:     at TLSWrap.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } } }

**Comment by synzen** [comment]
This is a normal error thrown by [d.js](https://github.com/discordjs/discord.js) for connection issues to the Discord API. You just have to make sure it's rebooted properly after it's crashed.

**Comment by mastermood** [comment]
Is there a way to automate this? so that if it disconnects it'll reconnect automatically? I used the systemd script from before.

**Comment by synzen** [comment]
Master Branch - https://github.com/synzen/Discord.RSS/wiki/Setup-(v2.2)#process-managers
Dev Branch - https://github.com/synzen/Discord.RSS/wiki/Setup#process-managers

These are just suggestions - you're free to use whatever you want that will keep a node js process running by rebooting it automatically after it exits
