### ISSUE TITLE
Change database engine

### ISSUE THREAD

**Issue by vpontin** [synzen/Discord.RSS#58]
Since sqlite3 package devs [arent going to fix the issue with their package and node 10.x](https://github.com/mapbox/node-sqlite3/issues/973) i want to know if is there any option/alternative database to use with the bot. H2 or other text-based can be good, or the old mysql/mariadb.

Or even change the package from sqlite3 to sqlite [because in that the issue was resolved](https://github.com/kriasoft/node-sqlite/issues/58).

Thanks in advance!

**Comment by Macley-Kun** [comment]
Try the dev branch!
That uses mongodb!

In the future everyone is gonna move to that so.

**Comment by vpontin** [comment]
Sadly [mongodb stopped being updated for raspbian](https://raspberrypi.stackexchange.com/questions/29208/mongodb-on-raspbian) (due to this OS being an ARM32 one, and raspberry team [arent willing to port it to 64](https://www.raspberrypi.org/forums/viewtopic.php?p=1249733&sid=550ae6487cdc18d5a7dd74cf7aab6248#p1249733)).

The version on apt is 2.4 and the most recent i found to install on internet [was 3.2](https://andyfelong.com/2018/03/mongodb-3-2-64-bit-running-on-raspberry-pi-3-with-caveats/). So, other alternative actively developed for raspbian would be appreciated, because i know more people would use a pi as a "bot box" (to self-host discord bots cheaply).

**Comment by Macley-Kun** [comment]
Mhm.. what about a free cloud solution? That you use a mongodb that’s in the cloud?

I assume that the developers don’t support your architecture due to age maybe? I’ve Never heard about the ARM32, so I assume it’s abit aged.

I don’t know any cloud service that fast what offers a mongodb. But I’m pretty sure there is one that’s free and workable :-)

Side note: users can always host for free in heroku with my instruction. For enough hours you would need a cc for activation.

**Comment by vpontin** [comment]
The question of ARM32 is the raspberry developers aren't willing to build raspbian into 64 because "switching to 64-bit brings almost nothing, not much more speed for example" (aka laziness?).

In fact the processor of raspberry is an ARM64, only the OS is compiled for 32.

Anyway, for a self-hosted home project i didnt see any advantages to using an external database (that's why i begin to self-host in first place: to run from third party hosting and to give more control over the bot).

Also i fear if i got an internet outage cuttting connection between the pi and DB it could corrupt it somehow.

**Comment by Macley-Kun** [comment]
The first part of your message is something we can't do, if enough users would suggest the devs to make the move, they probably would spent their time to it.
If the OS is compiled for 32, maybe you could use debian jessie (8), that one runs on quite low specs (few mb's only!)
The advantages you get is that you host completley free, and it's on a system that has probably more memory, cpu en bandwith.
If you have maybe another device that could support a mongodb, you could connect to that locally.
Also, if the internet is out, then i don't think your bot can recieve a input (like adding a rss-feed) in the first place.

**Comment by vpontin** [comment]
Thanks @synzen , will test this night!

**Comment by synzen** [comment]
There's now a version of the next major release that does not require mongo, please see https://github.com/synzen/Discord.RSS/wiki/Setup and follow the directions for a databaseless configuration.

**Comment by vpontin** [comment]
@synzen should i clone the `master` or `dev` branch?

**Comment by synzen** [comment]
The dev branch

**Comment by vpontin** [comment]
Thank you! Will close the issue as soon i can test this on my pi.

And just FYI: seems like sqlite3 guys [just updated it to be supported by node 10](https://github.com/mapbox/node-sqlite3/issues/973#event-1697306103).

**Comment by synzen** [comment]
3.0.0 has been marked and the SQL version is now unsupported - please use the newest version and report any problems in a new issue. Thanks.
