### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JustxMeg** [synzen/Discord.RSS#59]
`
npm ERR! Linux 4.15.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "discord.rss"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install discord.rss as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/rss/npm-debug.log
root@vps561467:~/rss#
`

**Comment by Macley-Kun** [comment]
Can you provide that npm-debug.log ?

**Comment by JustxMeg** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'discord.rss' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData discord.rss
8 silly fetchNamedPackageData discord.rss
9 silly mapToRegistry name discord.rss
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/discord.rss
13 verbose request uri https://registry.npmjs.org/discord.rss
14 verbose request no auth needed
15 info attempt registry request try #1 at 10:45:35 PM
16 verbose request id 0f756c651aca1414
17 http request GET https://registry.npmjs.org/discord.rss
18 http 200 https://registry.npmjs.org/discord.rss
19 verbose headers { date: 'Fri, 06 Jul 2018 20:45:36 GMT',
19 verbose headers   'content-type': 'application/json; charset=UTF-8',
19 verbose headers   'transfer-encoding': 'chunked',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'set-cookie':
19 verbose headers    [ '__cfduid=d5959ab50e7f68d689603a2947be4f77e1530909935; expires=Sat, 06-Jul-19 20:45:35 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
19 verbose headers   'cache-control': 'max-age=300',
19 verbose headers   'cf-cache-status': 'MISS',
19 verbose headers   'cf-ray': '4364ea7a3f7aa851-CDG',
19 verbose headers   etag: 'W/"ecdecf7a81f53d9cc7e4bb9b7a997294"',
19 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
19 verbose headers   'last-modified': 'Mon, 25 Jun 2018 11:49:52 GMT',
19 verbose headers   vary: 'accept-encoding, accept',
19 verbose headers   server: 'cloudflare',
19 verbose headers   'content-encoding': 'gzip' }
20 silly get cb [ 200,
20 silly get   { date: 'Fri, 06 Jul 2018 20:45:36 GMT',
20 silly get     'content-type': 'application/json; charset=UTF-8',
20 silly get     'transfer-encoding': 'chunked',
20 silly get     connection: 'keep-alive',
20 silly get     'set-cookie':
20 silly get      [ '__cfduid=d5959ab50e7f68d689603a2947be4f77e1530909935; expires=Sat, 06-Jul-19 20:45:35 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
20 silly get     'cache-control': 'max-age=300',
20 silly get     'cf-cache-status': 'MISS',
20 silly get     'cf-ray': '4364ea7a3f7aa851-CDG',
20 silly get     etag: 'W/"ecdecf7a81f53d9cc7e4bb9b7a997294"',
20 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
20 silly get     'last-modified': 'Mon, 25 Jun 2018 11:49:52 GMT',
20 silly get     vary: 'accept-encoding, accept',
20 silly get     server: 'cloudflare',
20 silly get     'content-encoding': 'gzip' } ]
21 verbose get saving discord.rss to /root/.npm/registry.npmjs.org/discord.rss/.cache.json
22 silly install normalizeTree
23 silly loadCurrentTree Finishing
24 silly loadIdealTree Starting
25 silly install loadIdealTree
26 silly cloneCurrentTree Starting
27 silly install cloneCurrentTreeToIdealTree
28 silly cloneCurrentTree Finishing
29 silly loadShrinkwrap Starting
30 silly install loadShrinkwrap
31 silly loadShrinkwrap Finishing
32 silly loadAllDepsIntoIdealTree Starting
33 silly install loadAllDepsIntoIdealTree
34 silly rollbackFailedOptional Starting
35 silly rollbackFailedOptional Finishing
36 silly runTopLevelLifecycles Starting
37 silly runTopLevelLifecycles Finishing
38 silly install printInstalled
39 verbose stack Error: Refusing to install discord.rss as a dependency of itself
39 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
39 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
39 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
39 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
39 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
39 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
39 verbose stack     at Array.forEach (<anonymous>)
39 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
39 verbose stack     at Array.forEach (<anonymous>)
39 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
40 verbose cwd /root/rss
41 error Linux 4.15.0-24-generic
42 error argv "/usr/bin/node" "/usr/bin/npm" "install" "discord.rss"
43 error node v8.10.0
44 error npm  v3.5.2
45 error code ENOSELF
46 error Refusing to install discord.rss as a dependency of itself
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]

**Comment by synzen** [comment]
Please provide your exact steps to reproduce the error

**Comment by JustxMeg** [comment]
I get it when I do npm install discord.rss

**Comment by synzen** [comment]
That depends on how you want to configure it. See https://github.com/synzen/Discord.RSS/wiki/Setup step 7

**Comment by JustxMeg** [comment]
Embedding it isnt working too. :/

**Comment by Macley-Kun** [comment]
@JustxMeg you can join the Discord server, might be more appriopate to ask :-)

https://discord.gg/NFeReE (1 day)

**Comment by synzen** [comment]
Please provide more details other than that it isn't working - what you're trying to do, what you did, code, etc. etc.

Joining the support server is also possible as Macley linked it for more immediate responses, if you'd like.
