### ISSUE TITLE
Charset

### ISSUE THREAD

**Issue by AnthonyGates** [synzen/Discord.RSS#64]
Hello! 

I am using your bot on my server in connection with a hungarian Simple Machines Forum. 

Unfortunately, it does not work perfectly becouse the hungarian accentuated letters (áéíűőúóüÖ ÁÉÍŰŐÚÓÜÖ).
These letters are replaced with a � character.
Can we set the character encoding?

**Comment by synzen** [comment]
What is the specific feed URL where this happens?

**Comment by AnthonyGates** [comment]
Its https://westrpg.hu/index.php?action=.xml;type=rss

**Comment by synzen** [comment]
Thanks, I'll work on it. Though for the record I don't think this will happen if you are on master branch before the dependency change from needle to node-fetch.

**Comment by synzen** [comment]
Added conversions in dev branch https://github.com/synzen/Discord.RSS/commit/d3f96deaa25bf4b26e5216aa2c1e9c851ce80cd4
