### ISSUE TITLE
Cloudflare blocks bot to add feed.

### ISSUE THREAD

**Issue by JamieSinn** [synzen/Discord.RSS#7]
Attempting to add this feed: https://www.ecocitycraft.com/forum/forums/ban-appeals-complaints.14/index.rss

This is behind a cloudflare protected site, and we need it to be able to access it. 

If you're willing, email me jamiesinn at ecocitycraft dot com your IP for the host, and I'll whitelist it for cloudflare.

**Comment by synzen** [comment]
Just added something to fix to this, you should be able to add the feed now. Will probably come up with a better solution later when I get the time but should be functional now.

**Comment by JamieSinn** [comment]
Great thanks!

**Comment by SliDeeN** [comment]
Hello @JamieSinn, i have the same issue for this feed : https://www5.yggtorrent.fi/rss?action=generate&type=subcat&id=2161
Can you please fix that ?
Thank you :)
