### ISSUE TITLE
Prefix alias (per guild?)

### ISSUE THREAD

**Issue by Macley-Kun** [synzen/Discord.RSS#70]
The current way to change the prefix is by changing it here: https://github.com/synzen/Discord.RSS/blob/master/config.json#L11

However, it might be handy to use a command to change this globally. Example:
(owner only)
`~prefix .` what should change the global prefix for the bot to: `.rss`.

Optionally, this could maybe be done per guild base. Example:
(Manage Channel)
`~rssprefix .` what should change the guild prefix for the bot to: `.rss`.

However, due to users may be forgetting what their prefix was. It would be better to keep the fallback prefix. So users can always rely on the wiki whatever their custom alias may be.

(Tip to S64: hardcode the alias prefix to be only x characters long. As some users on other bots who have this functionality made some pretty insane prefixes. Like a very long sentence or something with spaces in it.)

**Comment by synzen** [comment]
Sure, when I have it done I'll close the issue with the commit that'll have this implemented. It'll be per guild since it's silly for a global change because config json *is* the global config, and we can't have servers changing the global prefix all willy nilly

**Comment by synzen** [comment]
Custom prefix support has been added https://github.com/synzen/Discord.RSS/commit/c6ef7764de8deaa3835db141228f86111ceace27

**Comment by Macley-Kun** [comment]
<3
