### ISSUE TITLE
Decode failing for windows-1251 feed

### ISSUE THREAD

**Issue by synzen** [synzen/Discord.RSS#71]
http://4pda.ru/feed/rss.xml using windows-1251 decoding incorrectly:

![](https://media.discordapp.net/attachments/268914102280257537/500029290159669249/unknown.png)

In case the feed ever goes offline, XML is at https://pastebin.com/raw/i8AzNeVW

**Comment by Chilace** [comment]
https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding

**Comment by synzen** [comment]
The way it is currently being done now is for several reasons

- The response is not directly handled by me, it's piped to feedparser. I could first decode it myself and then hand over the decoded to feedparser, but I'm unsure whether or not that that will affect performance (and one small change for thousands can be big) 
- If I decide to decode right before sending it to discord, I must input strings because I no longer have access to the original buffer
- I am not even sure if this is the cause of the issue since I have had no complaints other than this one

A more complex issue that I have yet to dedicate time to

**Comment by synzen** [comment]
Fixed in https://github.com/synzen/Discord.RSS/commit/e188ea9a9618170d175b0015dc01e0f6e403f6d8, where you now manually specify feed encodings in `config.feeds.decode` with the feed URL as key, and its encoding as the value.
