### ISSUE TITLE
Discord bot doesn't answer in a specific channel

### ISSUE THREAD

**Issue by DannyTTH** [synzen/Discord.RSS#76]
Hi,

After I added an RSS feed (~rssadd http://eune.leagueoflegends.com/hu/rss.xml) to a channel, the bot didn't answer any kind of commands. O.o

**Comment by synzen** [comment]
Check your permissions

If this is an issue related to the public bot, please use the Discord and not github. This github is not for public bot support.

**Comment by DannyTTH** [comment]
Oh, sorry then. :/ Could you link the Discord server for me?

**Comment by synzen** [comment]
Please see https://www.reddit.com/r/discordapp/comments/5n9l6w/discordrss_an_rss_bot/
