### ISSUE TITLE
Include eslintrc config for StandardJS

### ISSUE THREAD

**Issue by synzen** [synzen/Discord.RSS#81]

**Comment by Chilace** [comment]
ok let's try it

installed globally to not modify the `package.json`:
```bush
npm i -g eslint eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node eslint-config-standard
```
created config `.eslintrc.json`:
```json
{
    "extends": "standard"
}
```
tried linting:
![2018-12-05 11-28-22 config js - discord rss - visual studio code](https://user-images.githubusercontent.com/22879802/49500860-b91e2e80-f882-11e8-899c-db89e516eaa9.png)

hmm, but what about `config.js` with double quote?
![2018-12-05 11-29-19 config js - discord rss - visual studio code](https://user-images.githubusercontent.com/22879802/49500956-e36fec00-f882-11e8-9b75-bd935ee753e9.png)

what the heck?

**Comment by Chilace** [comment]
Ah, never mind, i got it - default formatter does not output the fixable code with `--fix-dry-run` option.
One more try:
```bash
eslint .
```
![2018-12-05 14-04-00 discord rss - visual studio code](https://user-images.githubusercontent.com/22879802/49509665-0c01e100-f897-11e8-9735-4b643c576a86.png)

definitely need custom rules here

**Comment by synzen** [comment]
Oh I had forgotten to vet the code in those 2 files. Thanks for looking into it, I'll get to it

**Comment by synzen** [comment]
Though I'm curious why you'd like to exclude the dependencies from package.json - if you want the eslint config, you'd want them in the package no?

**Comment by shikhir-arora** [comment]
Random interjection, if it helps, I've been using StandardJS for a while (~2 years) now for this simple Karma bot: https://github.com/shikhir-arora/karma-simple (with [**really** strict rules](https://github.com/shikhir-arora/karma-simple/blob/master/.eslintrc.yaml)) and it's part of the [Travis build too](https://github.com/shikhir-arora/karma-simple/blob/master/.travis.yml#L13) (yes, there's redudant eslint/standard in the Travis check 😂). Can see the [package.json](https://github.com/shikhir-arora/karma-simple/blob/master/package.json#L50) we use ¯\\\_(ツ)_/¯

**Comment by Chilace** [comment]
As for eslint, I prefer to install it globally (because it is used in all projects) and use one general config in home dir and separate configs for some projects in their dirs.
If you want to install it locally in dev dependencies , go ahead - it doesn't matter.

**Comment by synzen** [comment]
https://github.com/synzen/Discord.RSS/commit/c890b39b2fb8cbac0cded767aa23c6f518917e12 eslint config is added now, let me know if there are any issues with it

**Comment by Chilace** [comment]
`npm ci`  to install exactly what is in a lockfile:
![2018-12-09 14-27-33 cmder](https://user-images.githubusercontent.com/22879802/49696693-bd1db980-fbbe-11e8-81e7-e9ab81c09d51.png)
Despite the fact that eslint is present in package.json, it is somehow missing in package-lock.json

**Comment by synzen** [comment]
thanks, added it https://github.com/synzen/Discord.RSS/commit/7ee85b911c68ca3844940a453e8604138e7238b0
