### ISSUE TITLE
Folder storage doesn't initialize?

### ISSUE THREAD

**Issue by urban-martin** [synzen/Discord.RSS#87]
Using 4.0.0 and 4.0.1 programmatically, the bot seems to accept and parse commands but does not execute them.  I have tried many commands including rssadd, rssrefresh, rsstest, rssdump, and rsshelp all with the same result.

Regardless of the command run, the response received is "This command is disabled while booting up, please wait."  This seems to be related to the storage initialization (via messages.js and storage.js).  I have tested this with both absolute and relative paths to the database folder URI.  Running on Ubuntu 18.04, Node 8.10.0, npm 3.5.2.

Attached is a screen shot of bot output while running (several commands were run against it, but output doesn't reflect that).

![discord rss_log](https://user-images.githubusercontent.com/23488406/50978405-94385f00-14b1-11e9-895f-e306b250e2b9.png)

**Comment by synzen** [comment]
Go ahead and try the recent push master now, should be fixed - it wasn't booting up since it wasn't properly checking for databaseless

**Comment by urban-martin** [comment]
It's definitely getting further but it looks like maybe it is not initializing the guild or something.  I can run rsshelp just fine.  The bot processes an rssadd command but generates an error that the appropriate json file in the db folder doesn't exist.  When I create an empty file with that filename and try again I get "Could not begin feed addition validation (SyntaxError: Unexpected end of JSON input)".

I also receive a few other errors when starting the server:
"UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir './events'"
"UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)"

This is an awesome project btw.  Thanks so much for making it public and the quick response!

**Comment by urban-martin** [comment]
Oops, yes, I was on dev.  Replaced with current master and everything seems to be working so far.  Thanks again!
