### ISSUE TITLE
Check the need for migration before running the bot

### ISSUE THREAD

**Issue by Chilace** [synzen/Discord.RSS#88]
In some environments, it is difficult to automate the process of updating the bot because the process manager immediately restarts the bot after trying to stop it.
It would be great if, during the boot process, the need to migrate the database was checked and, if necessary, the migration was started before logging in.

Maybe executing shell command:
```bash
git diff --exit-code HEAD~ -- ./update.js
```
Although it has a flaw - it will always diff until the next commit with an unchanged `./update.js`, it is more suitable for a one-time post-merge check.

**Comment by synzen** [comment]
Updates are now automated! Guild documents will now be versioned, and whenever its version is less than the latest available in `./updates`, it will run the update for every version after the document's version, including the latest one.
