### ISSUE TITLE
Bot stuck on booting

### ISSUE THREAD

**Issue by FraWolf** [synzen/Discord.RSS#90]
Hello, I’m using the npm package because I’ve already a bot and I don’t want a new one for rss, but when I use any type of rss command it says: “This command is disabled while booting up, please wait.”
Any fix? (I’m hosting the bot on glitch.com)

**Comment by synzen** [comment]
Make sure that you're on version 4.0.2 (type ~rssversion. If nothing shows up, your version is outdated below 4.0.0). If you're updated, please indicate whether you're using databaseless or mongodb, and if you can, provide steps to reproduce

**Comment by FraWolf** [comment]
I’ve sent you a pm on discord

**Comment by synzen** [comment]
Problem was using an outdated version of the package (3.0.0)
