### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by imaydaydl** [synzen/Discord.RSS#91]
Good day!
Sorry to address with a possibly stupid question, but I do not have sufficiently deep knowledge in this area. I installed your bot on my discord server. Works. And thanks for that. But since the coding on my site cp1251_general_ci I get the import of news in stacc characters.
��������� ������ � ��������� ceh9 �� ���� �������� �������

I already changed the encoding from utf-8 to cp1251 in files FlattenedJSON.js and Article.js, but it did not help. Ready to pay for help.

**Comment by synzen** [comment]
As Chilace said. Don't modify the original source, use `config.feeds.decode` in the form of

```
{
"url1": "original_encoding",
"url2": "original_encoding_2"
}
```

**Comment by Macley-Kun** [comment]
Think issue can be resolved?
