### ISSUE TITLE
How to restore from backup

### ISSUE THREAD

**Issue by D3rise** [synzen/Discord.RSS#93]
I have installed, configured, and created the backup of a bot, and I want to restore from backup. How I can do this? In wiki nothing about this.

**Comment by Macley-Kun** [comment]
1. Make sure on your self host bot that you have admin id of your discord account in.
2. Move that backup file into discord, and type in <yourbotprefix>restore <idserver> and hit enter.
Bot should say it worked

**Comment by D3rise** [comment]
That's worked! Thx!
