### ISSUE TITLE
How to host on Heroku for free without credit card

### ISSUE THREAD

**Issue by codeinteger6** [synzen/Discord.RSS#95]
The Heroku deploy button found on the bot readme uses add-ons to simplify the process and do most of the work for you, but Heroku has a requirement to provide your credit card info (even though its free) to verify your account and use any Heroku add-on. But what if you don't want to give your credit card info or some other reason? That is what this guide will teach you. You will not be losing anything by doing this method, however the process is a bit more complicated as we are not using these add ons to do everything automatically. If you follow this guide carefully I guarantee you will not run into any issues!

### **1. Create Discord bot application**

Go to https://discordapp.com/developers/applications/, create a new application and name it. Then go to the Bot tab, select Add Bot, confirm then name your bot and upload an avatar. This is what your bot will look like in Discord.

_If you don't want others to be able to add your bot turn off the Public Bot setting._

On that same page you will find your Token. You will need this later. **Do not share this token with anyone else!!!!**

### **2. Create MongoDB Atlas Database**

Go to https://www.mongodb.com/cloud/atlas and create an account if you don't already have one. Once you're logged in follow the instructions to create a cluster. Choose a server marked FREE TIER AVAILABLE, make sure the Cluster Tier is M0 and press Create Cluster.

![image](https://user-images.githubusercontent.com/44692189/54491346-16953300-48e8-11e9-9c81-3c58c338ff79.png)

Your cluster will take a few minutes to get ready. During this time go to the Security tab, press Add New User. Choose a username and a password (you will need the password later), check that the User Privileges are set to "Read and Write to any database" and press Add User.

Next you want to go to IP Whitelist, add IP and select Allow Access from Anywhere. Click Confirm.

After your cluster is ready click Connect found in the Overview screen.

![image](https://user-images.githubusercontent.com/44692189/54491363-2b71c680-48e8-11e9-8b67-c60200f1a4e1.png)

Select Connect Your Application, set Driver to Node.js and Version 2.2.12 or later. You will need the Connection String Only (not Full Driver Example) later on in this tutorial.

![image](https://user-images.githubusercontent.com/44692189/54491366-3593c500-48e8-11e9-9038-5b2c35b3be8d.png)

### **3. Deploy Bot to Heroku**

**If you don't already have [Git](https://www.atlassian.com/git/tutorials/install-git) and [Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli) on your computer then download them now.**

Download the master branch to your computer and extract the zip file. Right click inside that extracted folder and select Git Bash Here.

First log in to Heroku using the command `heroku login`.

Then type the following commands in order to deploy the bot to Heroku. (Replace APPNAMEHERE with any name you want)

```
git init
heroku create APPNAMEHERE
git add .
git commit -am "make it better"
git push heroku master

```
### **4. Configure config vars**

Once you have deployed the bot, go to your bot application on https://dashboard.heroku.com/apps and select the settings tab.

Add the following config vars:

`DRSS_BOT_CONTROLLER_IDS` - Your Discord User ID (check [here](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) if you're unsure)

`DRSS_BOT_PREFIX` - Type the prefix you want to use for commands

`DRSS_BOT_TOKEN` - Your bot token from Discord developer portal.

`DRSS_DATABASE_URI` - Your MongoDB connection string (replace `<password>` with your MongoDB password you created earlier and remove `&retrywrites=true` at the end of the string

`DRSS_FEEDS_REFRESH_TIME_MINUTES` - Set an interval (in minutes) how often you want the bot to check for new content.

![image](https://user-images.githubusercontent.com/44692189/54493771-ea84ac80-48fd-11e9-9181-b6f626394615.png)

### **5. Start the bot**

Go to the Resources tab in your Heroku application, turn off the web dyno and turn on the bot dyno.

![image](https://user-images.githubusercontent.com/44692189/54493794-346d9280-48fe-11e9-9d61-ada20bd03468.png)

### **6. Invite the bot**

Use one of the below URLs replacing the `INSERTHERE` with the Client ID from the Discord developer portal to invite the bot to your server.

With Role: https://discordapp.com/oauth2/authorize?client_id=INSERTHERE&scope=bot&permissions=19456
Without Role: https://discordapp.com/oauth2/authorize?client_id=INSERTHERE&scope=bot

**If you followed all these steps correctly, your bot should be up and running!**

**Comment by synzen** [comment]
Thanks for the writeup and contribution! I've added it to the Setup page. I am a bit concerned about the use of images since they can be easily outdated if they decide to update their UI, but it is better than nothing

**Comment by Anonymyous678** [comment]
How i can deploy manually discord rss bot without web dashboard?

**Comment by codeinteger6** [comment]
@Anonymyous678 skip step 4, and on step 5 skip adding `DRSS_WEB_ENABLED`, `DRSS_WEB_REDIRECT_URI`, `DRSS_WEB_CLIENT_ID`, `DRSS_WEB_CLIENT_SECRET` and `DRSS_REDIS_URI`. Once you have deployed the bot in step 6, go to the resources tab, disable web and enable the worker. You don't need to do step 7 as workers don't need to be pinged to stay online.

**Comment by Sikksens** [comment]
Has anything changed with this setup?

everything seems to run ok, but when signing into the web UI, the bot doesn't pick up any of my servers and I get these errors:

![image](https://user-images.githubusercontent.com/15923337/85048476-a5e86080-b193-11ea-8406-1b4dc412c33f.png)

**Comment by MicaelJarniac** [comment]
> Has anything changed with this setup?
> 
> everything seems to run ok, but when signing into the web UI, the bot doesn't pick up any of my servers and I get these errors:
> 
> ![image](https://user-images.githubusercontent.com/15923337/85048476-a5e86080-b193-11ea-8406-1b4dc412c33f.png)
> 
> Update:
> Seems like it was related to a caching issue with Redis and a preexisting bot application.

I'm having a similar problem. I have never used Heroku before, so a preexisting app shouldn't be the cause, at least for me.

**Comment by Sikksens** [comment]
Are you using an existing bot application from Discord?
I had to just create a new one with a new token etc and it worked out.

**Comment by MicaelJarniac** [comment]
I'm using a new one, created just for this purpose.

**Comment by MicaelJarniac** [comment]
Mine does work most of the time, but sometimes it just breaks and I have to restart it a few times to get it working again.

And even when it's working normally, I still get the **Cannot read property 'data' of null** warning.

**Comment by nullbasis** [comment]
I got as far as deploying the app on Heroku, but it seems to have crashed immediately.

> 2020-09-15T20:29:26.139147+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=xandrss.herokuapp.com request_id=1ef969f0-f49f-4e3e-adc8-f6fabaabe02c fwd="67.162.127.233" dyno= connect= service= status=503 bytes= protocol=https

I don't think I did anything wrong. I did skip the web dashboard settings because I don't intend to use it.

**Comment by JChace029** [comment]
This line is confusing me a bit:

DRSS_DATABASE_URI - Your MongoDB connection string (replace <password> with your MongoDB password you created earlier and also replace <dbname> with test)

**Remember the password and endpoint details from your redislabs account? Add them in the format given above.**

What exactly does that mean? Am I adding another line of DRSS_DATABASE_URI with those credentials?

**Comment by codeinteger6** [comment]
> This line is confusing me a bit:
> 
> DRSS_DATABASE_URI - Your MongoDB connection string (replace with your MongoDB password you created earlier and also replace with test)
> 
> **Remember the password and endpoint details from your redislabs account? Add them in the format given above.**
> 
> What exactly does that mean? Am I adding another line of DRSS_DATABASE_URI with those credentials?

Sorry that was for DRSSWEB_DATABASE_REDIS. I have updated the guide.

**Comment by rdarteda** [comment]
I can't access the web interface for some reason. these are the logs I have when trying to access the website

`2021-03-17T21:28:03.946281+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2021-03-17T21:28:04.007862+00:00 heroku[web.1]: Stopping process with SIGKILL
2021-03-17T21:28:04.226614+00:00 heroku[web.1]: Process exited with status 137
2021-03-17T21:28:04.352263+00:00 heroku[web.1]: State changed from starting to crashed
2021-03-17T21:28:05.839674+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=<appname>.herokuapp.com request_id=************************************** fwd="73.***.***.***" dyno= connect= service= status=503 bytes= protocol=https
2021-03-17T21:28:07.409123+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=<appname>.herokuapp.com request_id=************************************** fwd="73.***.***.***" dyno= connect= service= status=503 bytes= protocol=https`

**Comment by Reacien** [comment]
What exactly should be entered in the `DRSS_START` config var?

**Comment by Siphyshu** [comment]
> You can add additional config vars by following [this page](https://docs.discordrss.xyz/configuration/environment-variables).

The link is broken, should be [this](https://docs.monitorss.xyz/configuration/environment-variables) instead.

**Comment by codeinteger6** [comment]
@Siphyshu fixed, thanks

**Comment by tecaspt** [comment]
How can I use freshping to ping MongoDB instead?
I have no issues with Heroku going idle, but my bot randomly deletes all feeds and settings stored, after which I encounter MongoDB paused (so I assume this is the issue). How do I ping it or avoid it pausing automatically?

**Comment by codeinteger6** [comment]
@tecaspt you don't need to ping the MongoDB database. It only pauses if you don't use the bot for several weeks

**Comment by rosjoshuarecto** [comment]
![image](https://user-images.githubusercontent.com/63394095/139819501-c303631d-9823-4f1b-a85e-17dcf5f0aca3.png)

how can i fix this one?

**Comment by amblerkr** [comment]
There's something wrong. I tried to install a new bot in that way, but it failed. I've already installed bot twice. I think there was a problem as MongoDB was updated. Can you help me?

**Comment by infinitepower18** [comment]
Sadly Heroku will be terminating their free services this year on Nov 28…

https://techcrunch.com/2022/08/25/heroku-announces-plans-to-eliminate-free-plans-blaming-fraud-and-abuse/

**Comment by amblerkr** [comment]
> Sadly Heroku will be terminating their free services this year on Nov 28…
> 
> https://blog.heroku.com/next-chapter

Is there any easy way for me to move the current bot within 10 dollars? If you have, please share it with me.
