### ISSUE TITLE
How to allow line breaks in news article description?

### ISSUE THREAD

**Issue by therealgorgan** [synzen/Discord.RSS#98]
Hello, 

We're using RSS for our video game development patch notes and announcements and I'm wanting to allow line breaks in the body/description of the article. Right now it strips them and replaces with a space. I've been digging thru the files for a while and can't seem to make sense of where they are being stripped, so that I can intervene and ask it to instead convert to \n so that Discord will show a line break when it's printed. 

Any help will be appreciated. Thank you!

**Comment by therealgorgan** [comment]
My RSS Feed: 
```<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <title>Legends of Ultima: Patch Notes</title>
    <link>https://news.legendsofultima.online</link>
    <description>Legends of Ultima: Patch Notes</description>
    <language>en-us</language>
    <managingEditor>contact@legendsofultima.online</managingEditor>
    <webMaster>contact@legendsofultima.online</webMaster>
    <copyright>2019</copyright>
    
  <item><title>PVP Balance Pass</title><description><![CDATA[:nauseated_face: Poisoning Changes
- Will now only block 50% of the healing received when poisoned.
- When curing with potions, bandages or spells if the first try fails each subsequent try up to 3 total will see the chance raise by it's base value. - Each type of curing is separate, a fail on a spell cure will not add to the chances of curing next using a potion.
- A regular cure potion has a 25% chance to cure greater poison, after the first fail it would be 50% and after the second fail it would be 75% on the third try.
- This means a greater cure potion will have a 100% chance to cure a greater poison on the second try.

:sake: Potions
- All potions now share a 2 second global cooldown.

:syringe: Bandages
- Chance to slip when moving increased]]></description><link>http://news.legendsofultima.online/</link><author>Nek</author><pubDate>Wed, 20 Mar 2019 08:35:48 +0000</pubDate></item></channel>
</rss>
```

My feed config: ```{
  "name": "Bot Testing",
  "id": "557858490786250763",
  "sources": {
    "-1646290076newslegendsofultimaonline>36782": {
      "title": "Untitled",
      "link": "http://news.legendsofultima.online/patchnotes.xml",
      "channel": "557858490786250765",
      "addedOn": "2019-03-20T10:05:21.219Z",
      "embeds": [
        {
          "title": "{title}",
          "description": "{description:newline}",
          "author_name": "Legends of Ultima: Patch Note",
          "timestamp": "{date}",
          "url": "http://news.legendsofultima.online",
          "footer_text": "Written by: {author} @ {date}",
          "footer_icon_url": "https://cdn.discordapp.com/icons/369023244038045697/cc6674edd991beb6239d83f28d44b732.png",
          "author_icon_url": "https://cdn.discordapp.com/icons/369023244038045697/cc6674edd991beb6239d83f28d44b732.png"
        }
      ],
      "message": "{empty}",
      "regexOps": {
        "description": [
          {
            "name": "newline",
            "search": {
              "custom": true,
              "flags": "g",
              "regex": "\\s(\\[(?:Fixed|Changes|New)| *- )|\\*-- Delivered by Feed43 service\\*"
            },
            "replacementDirect": "\n$1"
          }
        ]
      }
    }
  }
}```

**Comment by synzen** [comment]
Is the feed link available to test? I will take a look at it later today, but normally HTML line breaks <br />, or lists should be converted to new lines

**Comment by therealgorgan** [comment]
Thank you! It's http://news.legendsofultima.online/patch notes.xml

**Comment by therealgorgan** [comment]
Or rather http://news.legendsofultima.online/patchnotes.xml

**Comment by synzen** [comment]
No problem,

![image](https://user-images.githubusercontent.com/18688793/54712804-9c50f280-4b23-11e9-9604-04a28b934f63.png)

there doesn't appear to be any new lines or line breaks in the xml. If you have control over the feed contents, it would be best if you formatted it with HTML, such as `<br />`

**Comment by therealgorgan** [comment]
![image](https://user-images.githubusercontent.com/33201476/54746754-f771fc00-4b9a-11e9-9cd6-b1cabe324f83.png)
Much better! Thank you so much for your guidance. :)
